import type { TourPackage } from "../types";
import { getTourHeroImageSrc } from "../tour-hero-images";
import { sharedExcluded, sharedIncluded } from "./shared";

/** Premium curated catalogue — hand-picked multi-day journeys and day tours. */
export const CATALOG_PACKAGES: TourPackage[] = [
{
    slug: "4-days-ella-train-escape",
    title: "4 Days Ella Train Escape",
    durationDays: 4,
    destinationSlugs: ["kandy", "nuwara-eliya", "ella"],
    categoryIds: ["custom-private", "train-journeys", "hill-country-tea"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Train segment", "Nine Arches", "Tea stops"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-ella-train-escape",
    galleryIds: ["hero-ella-train-escape", "kandy-hero", "nuwara-eliya-hero", "ella-hero"],
    seo: {
      title: "4 Days Ella Train Escape | Private Chauffeur Tour | Quick Pick",
      description: "Scenic rail through tea valleys. 4-day private chauffeur journey across Kandy, Nuwara Eliya, Ella with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/4-days-ella-train-escape",
      ogImage: getTourHeroImageSrc("hero-ella-train-escape"),
      ogTitle: "4 Days Ella Train Escape | Q Pick",
      twitterTitle: "4 Days Ella Train Escape",
      twitterDescription: "Scenic rail through tea valleys",
      keywords: ["4 day Sri Lanka tour", "private chauffeur Sri Lanka", "Kandy", "Nuwara Eliya", "Ella", "train journeys", "hill country tea", "custom private"],
      intro: "Scenic rail through tea valleys. This 4-day private chauffeur journey visits Kandy, Nuwara Eliya, Ella — rail lovers with limited time. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "kandy", title: "Discover Kandy", description: "Explore Kandy with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 2, destinationSlug: "nuwara-eliya", title: "Discover Nuwara Eliya", description: "Explore Nuwara Eliya with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 3, destinationSlug: "ella", title: "Discover Ella", description: "Explore Ella with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 4, destinationSlug: "ella", title: "Departure & onward", description: "Private transfer toward Colombo or Bandaranaike International Airport — or continue your custom route with Q Pick." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    badge: "new",
    popular: false,
    publishedAt: "2026-03-19",
    idealFor: "Rail lovers with limited time",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
{
    slug: "5-days-mirissa-whale-coast",
    title: "5 Days Mirissa Whale Coast",
    durationDays: 5,
    destinationSlugs: ["galle", "mirissa", "bentota"],
    categoryIds: ["custom-private", "beach-holidays", "wildlife-safari"],
    vehicleId: "sedan",
    startingPriceLkr: null,
    highlights: ["Mirissa coast", "Whale watching", "Galle Fort"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-mirissa-whale-coast",
    galleryIds: ["hero-mirissa-whale-coast", "galle-hero", "mirissa-hero", "bentota-hero"],
    seo: {
      title: "5 Days Mirissa Whale Coast | Private Chauffeur Tour | Quick Pick",
      description: "Whale season and fort heritage. 5-day private chauffeur journey across Galle, Mirissa, Bentota with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/5-days-mirissa-whale-coast",
      ogImage: getTourHeroImageSrc("hero-mirissa-whale-coast"),
      ogTitle: "5 Days Mirissa Whale Coast | Q Pick",
      twitterTitle: "5 Days Mirissa Whale Coast",
      twitterDescription: "Whale season and fort heritage",
      keywords: ["5 day Sri Lanka tour", "private chauffeur Sri Lanka", "Galle", "Mirissa", "Bentota", "beach holidays", "wildlife safari", "custom private"],
      intro: "Whale season and fort heritage. This 5-day private chauffeur journey visits Galle, Mirissa, Bentota — ocean wildlife enthusiasts. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "galle", title: "Discover Galle", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 2, destinationSlug: "mirissa", title: "Discover Mirissa", description: "Explore Mirissa with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 3, destinationSlug: "bentota", title: "Discover Bentota", description: "Explore Bentota with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 4, destinationSlug: "bentota", title: "Bentota at leisure", description: "Explore Bentota with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 5, destinationSlug: "bentota", title: "Departure & onward", description: "Private transfer toward Colombo or Bandaranaike International Airport — or continue your custom route with Q Pick." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    popular: false,
    publishedAt: "2026-03-20",
    idealFor: "Ocean wildlife enthusiasts",
    suggestedVehicleIds: ["sedan", "suv", "van"],
    published: true,
  },
{
    slug: "6-days-luxury-honeymoon-coast",
    title: "6 Days Luxury Honeymoon Coast",
    durationDays: 6,
    destinationSlugs: ["colombo", "galle", "bentota", "mirissa"],
    categoryIds: ["custom-private", "honeymoon", "luxury-escapes", "beach-holidays"],
    vehicleId: "luxuryVan",
    startingPriceLkr: null,
    highlights: ["Galle Fort", "Bentota", "Mirissa sunsets"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-luxury-honeymoon-coast",
    galleryIds: ["hero-luxury-honeymoon-coast", "colombo-hero", "galle-hero", "bentota-hero", "mirissa-hero"],
    seo: {
      title: "6 Days Luxury Honeymoon Coast | Private Chauffeur Tour | Quick Pick",
      description: "Fort romance and ocean villas. 6-day private chauffeur journey across Colombo, Galle, Bentota, Mirissa with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/6-days-luxury-honeymoon-coast",
      ogImage: getTourHeroImageSrc("hero-luxury-honeymoon-coast"),
      ogTitle: "6 Days Luxury Honeymoon Coast | Q Pick",
      twitterTitle: "6 Days Luxury Honeymoon Coast",
      twitterDescription: "Fort romance and ocean villas",
      keywords: ["6 day Sri Lanka tour", "private chauffeur Sri Lanka", "Colombo", "Galle", "Bentota", "Mirissa", "honeymoon", "luxury escapes", "beach holidays"],
      intro: "Fort romance and ocean villas. This 6-day private chauffeur journey visits Colombo, Galle, Bentota, Mirissa — coastal honeymooners. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "colombo", title: "Discover Colombo", description: "Explore Colombo with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 2, destinationSlug: "galle", title: "Discover Galle", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 3, destinationSlug: "bentota", title: "Discover Bentota", description: "Explore Bentota with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 4, destinationSlug: "mirissa", title: "Discover Mirissa", description: "Explore Mirissa with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 5, destinationSlug: "mirissa", title: "Mirissa at leisure", description: "Explore Mirissa with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 6, destinationSlug: "mirissa", title: "Departure & onward", description: "Private transfer toward Colombo or Bandaranaike International Airport — or continue your custom route with Q Pick." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    badge: "luxury",
    popular: false,
    publishedAt: "2026-02-23",
    idealFor: "Coastal honeymooners",
    suggestedVehicleIds: ["luxuryVan", "suv"],
    published: true,
  },
{
    slug: "6-days-pilgrimage-triangle",
    title: "6 Days Pilgrimage Triangle",
    durationDays: 6,
    destinationSlugs: ["kandy", "anuradhapura", "dambulla", "polonnaruwa"],
    categoryIds: ["custom-private", "pilgrimage", "cultural-heritage"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Temple of the Tooth", "Anuradhapura", "Dambulla caves"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-pilgrimage-triangle",
    galleryIds: ["hero-pilgrimage-triangle", "kandy-hero", "anuradhapura-hero", "dambulla-hero", "polonnaruwa-hero"],
    seo: {
      title: "6 Days Pilgrimage Triangle | Private Chauffeur Tour | Quick Pick",
      description: "Sacred sites across the island. 6-day private chauffeur journey across Kandy, Anuradhapura, Dambulla, Polonnaruwa with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/6-days-pilgrimage-triangle",
      ogImage: getTourHeroImageSrc("hero-pilgrimage-triangle"),
      ogTitle: "6 Days Pilgrimage Triangle | Q Pick",
      twitterTitle: "6 Days Pilgrimage Triangle",
      twitterDescription: "Sacred sites across the island",
      keywords: ["6 day Sri Lanka tour", "private chauffeur Sri Lanka", "Kandy", "Anuradhapura", "Dambulla", "Polonnaruwa", "pilgrimage", "cultural heritage", "custom private"],
      intro: "Sacred sites across the island. This 6-day private chauffeur journey visits Kandy, Anuradhapura, Dambulla, Polonnaruwa — faith-led group travel. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "kandy", title: "Discover Kandy", description: "Explore Kandy with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 2, destinationSlug: "anuradhapura", title: "Discover Anuradhapura", description: "Explore Anuradhapura with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 3, destinationSlug: "dambulla", title: "Discover Dambulla", description: "Explore Dambulla with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 4, destinationSlug: "polonnaruwa", title: "Discover Polonnaruwa", description: "Explore Polonnaruwa with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 5, destinationSlug: "polonnaruwa", title: "Polonnaruwa at leisure", description: "Explore Polonnaruwa with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 6, destinationSlug: "polonnaruwa", title: "Departure & onward", description: "Private transfer toward Colombo or Bandaranaike International Airport — or continue your custom route with Q Pick." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    popular: false,
    publishedAt: "2026-03-21",
    idealFor: "Faith-led group travel",
    suggestedVehicleIds: ["suv", "van", "miniCoach"],
    published: true,
  },
{
    slug: "8-days-festival-culture-kandy",
    title: "8 Days Festival Culture & Kandy",
    durationDays: 8,
    destinationSlugs: ["colombo", "kandy", "dambulla", "sigiriya", "negombo"],
    categoryIds: ["custom-private", "festival", "cultural-heritage"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Kandy festivals", "Temple visits", "Triangle icons"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-festival-culture-kandy",
    galleryIds: ["hero-festival-culture-kandy", "colombo-hero", "kandy-hero", "dambulla-hero", "sigiriya-hero", "negombo-hero"],
    seo: {
      title: "8 Days Festival Culture & Kandy | Private Chauffeur Tour | Quick Pick",
      description: "Perahera timing with heritage. 8-day private chauffeur journey across Colombo, Kandy, Dambulla, Sigiriya, Negombo with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/8-days-festival-culture-kandy",
      ogImage: getTourHeroImageSrc("hero-festival-culture-kandy"),
      ogTitle: "8 Days Festival Culture & Kandy | Q Pick",
      twitterTitle: "8 Days Festival Culture & Kandy",
      twitterDescription: "Perahera timing with heritage",
      keywords: ["8 day Sri Lanka tour", "private chauffeur Sri Lanka", "Colombo", "Kandy", "Dambulla", "Sigiriya", "Negombo", "festival", "cultural heritage", "custom private"],
      intro: "Perahera timing with heritage. This 8-day private chauffeur journey visits Colombo, Kandy, Dambulla, Sigiriya, Negombo — festival season visitors. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "colombo", title: "Discover Colombo", description: "Explore Colombo with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 2, destinationSlug: "kandy", title: "Discover Kandy", description: "Explore Kandy with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 3, destinationSlug: "dambulla", title: "Discover Dambulla", description: "Explore Dambulla with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 4, destinationSlug: "sigiriya", title: "Discover Sigiriya", description: "Explore Sigiriya with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 5, destinationSlug: "negombo", title: "Discover Negombo", description: "Explore Negombo with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 6, destinationSlug: "negombo", title: "Negombo at leisure", description: "Explore Negombo with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 7, destinationSlug: "negombo", title: "Negombo at leisure", description: "Explore Negombo with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 8, destinationSlug: "negombo", title: "Departure & onward", description: "Private transfer toward Colombo or Bandaranaike International Airport — or continue your custom route with Q Pick." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    popular: false,
    publishedAt: "2026-02-27",
    idealFor: "Festival season visitors",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
{
    slug: "9-days-honeymoon-paradise",
    title: "9 Days Honeymoon Paradise",
    durationDays: 9,
    destinationSlugs: ["negombo", "kandy", "nuwara-eliya", "ella", "bentota", "galle"],
    categoryIds: ["custom-private", "honeymoon", "luxury-escapes", "hill-country-tea"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Tea country", "Ella romance", "Coastal sunsets"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-honeymoon-paradise",
    galleryIds: ["hero-honeymoon-paradise", "negombo-hero", "kandy-hero", "nuwara-eliya-hero", "ella-hero", "bentota-hero", "galle-hero"],
    seo: {
      title: "9 Days Honeymoon Paradise | Private Chauffeur Tour | Quick Pick",
      description: "Intimate pacing through mist and ocean. 9-day private chauffeur journey across Negombo, Kandy, Nuwara Eliya, Ella, Bentota, Galle with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/9-days-honeymoon-paradise",
      ogImage: getTourHeroImageSrc("hero-honeymoon-paradise"),
      ogTitle: "9 Days Honeymoon Paradise | Q Pick",
      twitterTitle: "9 Days Honeymoon Paradise",
      twitterDescription: "Intimate pacing through mist and ocean",
      keywords: ["9 day Sri Lanka tour", "private chauffeur Sri Lanka", "Negombo", "Kandy", "Nuwara Eliya", "Ella", "Bentota", "Galle", "honeymoon", "luxury escapes", "hill country tea"],
      intro: "Intimate pacing through mist and ocean. This 9-day private chauffeur journey visits Negombo, Kandy, Nuwara Eliya, Ella, Bentota, Galle — newlyweds and romantic escapes. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "negombo", title: "Discover Negombo", description: "Explore Negombo with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 2, destinationSlug: "kandy", title: "Discover Kandy", description: "Explore Kandy with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 3, destinationSlug: "nuwara-eliya", title: "Discover Nuwara Eliya", description: "Explore Nuwara Eliya with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 4, destinationSlug: "ella", title: "Discover Ella", description: "Explore Ella with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 5, destinationSlug: "bentota", title: "Discover Bentota", description: "Explore Bentota with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 6, destinationSlug: "galle", title: "Discover Galle", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 7, destinationSlug: "galle", title: "Galle at leisure", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 8, destinationSlug: "galle", title: "Galle at leisure", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 9, destinationSlug: "galle", title: "Departure & onward", description: "Private transfer toward Colombo or Bandaranaike International Airport — or continue your custom route with Q Pick." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    badge: "luxury",
    popular: true,
    featuredRank: 10,
    publishedAt: "2026-01-18",
    idealFor: "Newlyweds and romantic escapes",
    suggestedVehicleIds: ["suv", "luxuryVan"],
    published: true,
  },
{
    slug: "10-days-ayurveda-wellness-journey",
    title: "10 Days Ayurveda Wellness Journey",
    durationDays: 10,
    destinationSlugs: ["negombo", "kandy", "bentota", "mirissa", "galle"],
    categoryIds: ["custom-private", "ayurveda-wellness", "luxury-escapes", "beach-holidays"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Wellness pacing", "Coastal calm", "Temple balance"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-ayurveda-wellness",
    galleryIds: ["hero-ayurveda-wellness", "negombo-hero", "kandy-hero", "bentota-hero", "mirissa-hero", "galle-hero"],
    seo: {
      title: "10 Days Ayurveda Wellness Journey | Private Chauffeur Tour | Quick Pick",
      description: "Recovery chapters woven into private travel. 10-day private chauffeur journey across Negombo, Kandy, Bentota, Mirissa, Galle with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/10-days-ayurveda-wellness-journey",
      ogImage: getTourHeroImageSrc("hero-ayurveda-wellness"),
      ogTitle: "10 Days Ayurveda Wellness Journey | Q Pick",
      twitterTitle: "10 Days Ayurveda Wellness Journey",
      twitterDescription: "Recovery chapters woven into private travel",
      keywords: ["10 day Sri Lanka tour", "private chauffeur Sri Lanka", "Negombo", "Kandy", "Bentota", "Mirissa", "Galle", "ayurveda wellness", "luxury escapes", "beach holidays"],
      intro: "Recovery chapters woven into private travel. This 10-day private chauffeur journey visits Negombo, Kandy, Bentota, Mirissa, Galle — wellness-focused travellers. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "negombo", title: "Discover Negombo", description: "Explore Negombo with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 2, destinationSlug: "kandy", title: "Discover Kandy", description: "Explore Kandy with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 3, destinationSlug: "bentota", title: "Discover Bentota", description: "Explore Bentota with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 4, destinationSlug: "mirissa", title: "Discover Mirissa", description: "Explore Mirissa with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 5, destinationSlug: "galle", title: "Discover Galle", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 6, destinationSlug: "galle", title: "Galle at leisure", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 7, destinationSlug: "galle", title: "Galle at leisure", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 8, destinationSlug: "galle", title: "Galle at leisure", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 9, destinationSlug: "galle", title: "Galle at leisure", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
      { day: 10, destinationSlug: "galle", title: "Departure & onward", description: "Private transfer toward Colombo or Bandaranaike International Airport — or continue your custom route with Q Pick." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    popular: false,
    publishedAt: "2026-01-22",
    idealFor: "Wellness-focused travellers",
    suggestedVehicleIds: ["suv", "luxuryVan"],
    published: true,
  },
{
    slug: "colombo-capital-discovery-day",
    title: "Colombo Capital Discovery Day",
    durationDays: 1,
    destinationSlugs: ["colombo"],
    categoryIds: ["custom-private", "day-tours", "classic-sri-lanka", "food", "private-chauffeur"],
    vehicleId: "sedan",
    startingPriceLkr: null,
    highlights: ["Lotus Tower viewpoints", "Galle Face Green", "Colombo dining stops"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-day-colombo",
    galleryIds: ["hero-day-colombo"],
    seo: {
      title: "Colombo Capital Discovery Day | Private Chauffeur Tour | Quick Pick",
      description: "Colombo skyline, colonial lanes, and Galle Face sunsets. 1-day private chauffeur journey across Colombo with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/colombo-capital-discovery-day",
      ogImage: getTourHeroImageSrc("hero-day-colombo"),
      ogTitle: "Colombo Capital Discovery Day | Q Pick",
      twitterTitle: "Colombo Capital Discovery Day",
      twitterDescription: "Colombo skyline, colonial lanes, and Galle Face sunsets",
      keywords: ["1 day Sri Lanka tour", "private chauffeur Sri Lanka", "Colombo", "day tours", "classic sri lanka", "food"],
      intro: "Colombo skyline, colonial lanes, and Galle Face sunsets. This 1-day private chauffeur journey visits Colombo — layover guests and city lovers. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "colombo", title: "Colombo discovery", description: "Explore Colombo with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["galle-fort-heritage-day", "sigiriya-rock-sunrise-day"],
    popular: false,
    publishedAt: "2026-03-01",
    idealFor: "Layover guests and city lovers",
    suggestedVehicleIds: ["sedan", "suv"],
    published: true,
  },
{
    slug: "galle-fort-heritage-day",
    title: "Galle Fort Heritage Day",
    durationDays: 1,
    destinationSlugs: ["galle"],
    categoryIds: ["custom-private", "day-tours", "cultural-heritage", "beach-holidays"],
    vehicleId: "sedan",
    startingPriceLkr: null,
    highlights: ["Galle Fort lighthouse", "Rampart walk", "Boutique streets"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-day-galle",
    galleryIds: ["hero-day-galle"],
    seo: {
      title: "Galle Fort Heritage Day | Private Chauffeur Tour | Quick Pick",
      description: "Dutch ramparts and Indian Ocean light. 1-day private chauffeur journey across Galle with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/galle-fort-heritage-day",
      ogImage: getTourHeroImageSrc("hero-day-galle"),
      ogTitle: "Galle Fort Heritage Day | Q Pick",
      twitterTitle: "Galle Fort Heritage Day",
      twitterDescription: "Dutch ramparts and Indian Ocean light",
      keywords: ["1 day Sri Lanka tour", "private chauffeur Sri Lanka", "Galle", "day tours", "cultural heritage", "beach holidays"],
      intro: "Dutch ramparts and Indian Ocean light. This 1-day private chauffeur journey visits Galle — history enthusiasts on the south coast. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "galle", title: "Galle discovery", description: "Explore Galle with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "sigiriya-rock-sunrise-day"],
    popular: false,
    publishedAt: "2026-03-02",
    idealFor: "History enthusiasts on the south coast",
    suggestedVehicleIds: ["sedan", "suv"],
    published: true,
  },
{
    slug: "sigiriya-rock-sunrise-day",
    title: "Sigiriya Rock Sunrise Day",
    durationDays: 1,
    destinationSlugs: ["sigiriya"],
    categoryIds: ["custom-private", "day-tours", "cultural-heritage", "classic-sri-lanka", "photography-tours"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Sigiriya summit", "Water gardens", "Fresco gallery"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-day-sigiriya",
    galleryIds: ["hero-day-sigiriya"],
    seo: {
      title: "Sigiriya Rock Sunrise Day | Private Chauffeur Tour | Quick Pick",
      description: "Lion Rock at first light. 1-day private chauffeur journey across Sigiriya with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/sigiriya-rock-sunrise-day",
      ogImage: getTourHeroImageSrc("hero-day-sigiriya"),
      ogTitle: "Sigiriya Rock Sunrise Day | Q Pick",
      twitterTitle: "Sigiriya Rock Sunrise Day",
      twitterDescription: "Lion Rock at first light",
      keywords: ["1 day Sri Lanka tour", "private chauffeur Sri Lanka", "Sigiriya", "day tours", "cultural heritage", "classic sri lanka"],
      intro: "Lion Rock at first light. This 1-day private chauffeur journey visits Sigiriya — early risers and photography guests. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "sigiriya", title: "Sigiriya discovery", description: "Explore Sigiriya with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    badge: "adventure",
    popular: false,
    publishedAt: "2026-03-03",
    idealFor: "Early risers and photography guests",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
{
    slug: "kandy-sacred-city-day",
    title: "Kandy Sacred City Day",
    durationDays: 1,
    destinationSlugs: ["kandy"],
    categoryIds: ["custom-private", "day-tours", "cultural-heritage", "pilgrimage"],
    vehicleId: "sedan",
    startingPriceLkr: null,
    highlights: ["Temple of the Tooth", "Kandy Lake", "Peradeniya option"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-day-kandy",
    galleryIds: ["hero-day-kandy"],
    seo: {
      title: "Kandy Sacred City Day | Private Chauffeur Tour | Quick Pick",
      description: "Temple of the Tooth and lake calm. 1-day private chauffeur journey across Kandy with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/kandy-sacred-city-day",
      ogImage: getTourHeroImageSrc("hero-day-kandy"),
      ogTitle: "Kandy Sacred City Day | Q Pick",
      twitterTitle: "Kandy Sacred City Day",
      twitterDescription: "Temple of the Tooth and lake calm",
      keywords: ["1 day Sri Lanka tour", "private chauffeur Sri Lanka", "Kandy", "day tours", "cultural heritage", "pilgrimage"],
      intro: "Temple of the Tooth and lake calm. This 1-day private chauffeur journey visits Kandy — spiritual travellers and families. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "kandy", title: "Kandy discovery", description: "Explore Kandy with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    popular: false,
    publishedAt: "2026-03-04",
    idealFor: "Spiritual travellers and families",
    suggestedVehicleIds: ["sedan", "suv"],
    published: true,
  },
{
    slug: "ella-highland-views-day",
    title: "Ella Highland Views Day",
    durationDays: 1,
    destinationSlugs: ["ella"],
    categoryIds: ["custom-private", "day-tours", "hill-country-tea", "adventure", "photography-tours"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Nine Arches Bridge", "Little Adam's Peak", "Tea valley cafés"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-day-ella",
    galleryIds: ["hero-day-ella"],
    seo: {
      title: "Ella Highland Views Day | Private Chauffeur Tour | Quick Pick",
      description: "Nine Arches and misty valleys. 1-day private chauffeur journey across Ella with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/ella-highland-views-day",
      ogImage: getTourHeroImageSrc("hero-day-ella"),
      ogTitle: "Ella Highland Views Day | Q Pick",
      twitterTitle: "Ella Highland Views Day",
      twitterDescription: "Nine Arches and misty valleys",
      keywords: ["1 day Sri Lanka tour", "private chauffeur Sri Lanka", "Ella", "day tours", "hill country tea", "adventure"],
      intro: "Nine Arches and misty valleys. This 1-day private chauffeur journey visits Ella — train stopovers and ridge walkers. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "ella", title: "Ella discovery", description: "Explore Ella with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    popular: false,
    publishedAt: "2026-03-05",
    idealFor: "Train stopovers and ridge walkers",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
{
    slug: "yala-wildlife-safari-day",
    title: "Yala Wildlife Safari Day",
    durationDays: 1,
    destinationSlugs: ["yala"],
    categoryIds: ["custom-private", "day-tours", "wildlife-safari", "photography-tours"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Jeep safari window", "Dry-zone lagoons", "Birdlife"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-day-yala",
    galleryIds: ["hero-day-yala"],
    seo: {
      title: "Yala Wildlife Safari Day | Private Chauffeur Tour | Quick Pick",
      description: "Leopard country at dawn. 1-day private chauffeur journey across Yala with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/yala-wildlife-safari-day",
      ogImage: getTourHeroImageSrc("hero-day-yala"),
      ogTitle: "Yala Wildlife Safari Day | Q Pick",
      twitterTitle: "Yala Wildlife Safari Day",
      twitterDescription: "Leopard country at dawn",
      keywords: ["1 day Sri Lanka tour", "private chauffeur Sri Lanka", "Yala", "day tours", "wildlife safari", "photography tours"],
      intro: "Leopard country at dawn. This 1-day private chauffeur journey visits Yala — safari enthusiasts with tight schedules. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "yala", title: "Yala discovery", description: "Explore Yala with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    badge: "adventure",
    popular: false,
    publishedAt: "2026-03-11",
    idealFor: "Safari enthusiasts with tight schedules",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
{
    slug: "anuradhapura-sacred-trail-day",
    title: "Anuradhapura Sacred Trail Day",
    durationDays: 1,
    destinationSlugs: ["anuradhapura"],
    categoryIds: ["custom-private", "day-tours", "cultural-heritage", "pilgrimage"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: ["Ruwanwelisaya", "Sacred Bodhi tree", "Monastery ruins"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-day-anuradhapura",
    galleryIds: ["hero-day-anuradhapura"],
    seo: {
      title: "Anuradhapura Sacred Trail Day | Private Chauffeur Tour | Quick Pick",
      description: "Ancient stupas and bodhi traditions. 1-day private chauffeur journey across Anuradhapura with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/anuradhapura-sacred-trail-day",
      ogImage: getTourHeroImageSrc("hero-day-anuradhapura"),
      ogTitle: "Anuradhapura Sacred Trail Day | Q Pick",
      twitterTitle: "Anuradhapura Sacred Trail Day",
      twitterDescription: "Ancient stupas and bodhi traditions",
      keywords: ["1 day Sri Lanka tour", "private chauffeur Sri Lanka", "Anuradhapura", "day tours", "cultural heritage", "pilgrimage"],
      intro: "Ancient stupas and bodhi traditions. This 1-day private chauffeur journey visits Anuradhapura — buddhist heritage pilgrims. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "anuradhapura", title: "Anuradhapura discovery", description: "Explore Anuradhapura with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    popular: false,
    publishedAt: "2026-03-07",
    idealFor: "Buddhist heritage pilgrims",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
{
    slug: "mirissa-southern-coast-day",
    title: "Mirissa Southern Coast Day",
    durationDays: 1,
    destinationSlugs: ["mirissa"],
    categoryIds: ["custom-private", "day-tours", "beach-holidays", "wildlife-safari"],
    vehicleId: "sedan",
    startingPriceLkr: null,
    highlights: ["Mirissa Beach", "Coconut Hill", "Whale watching season"],
    travelTips: [
      "Confirm entrance tickets and safari jeep hire in advance — your chauffeur coordinates timing.",
      "Pack modest clothing for temples and a light layer for hill country mornings.",
      "Share flight details early so arrival and departure transfers stay composed.",
    ],
    bestTimeToVisit: "Year-round with seasonal tweaks — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-day-mirissa",
    galleryIds: ["hero-day-mirissa"],
    seo: {
      title: "Mirissa Southern Coast Day | Private Chauffeur Tour | Quick Pick",
      description: "Coconut coves and ocean horizons. 1-day private chauffeur journey across Mirissa with flexible pacing and written quotes from Q Pick.",
      canonicalPath: "/tours/mirissa-southern-coast-day",
      ogImage: getTourHeroImageSrc("hero-day-mirissa"),
      ogTitle: "Mirissa Southern Coast Day | Q Pick",
      twitterTitle: "Mirissa Southern Coast Day",
      twitterDescription: "Coconut coves and ocean horizons",
      keywords: ["1 day Sri Lanka tour", "private chauffeur Sri Lanka", "Mirissa", "day tours", "beach holidays", "wildlife safari"],
      intro: "Coconut coves and ocean horizons. This 1-day private chauffeur journey visits Mirissa — whale season visitors. Your dedicated driver handles the road while you focus on temples, viewpoints, wildlife windows, and unhurried coastal afternoons. Every Q Pick tour is refined after a written review of your dates, vehicle preference, and pace.",
    },
    itinerary: [
      { day: 1, destinationSlug: "mirissa", title: "Mirissa discovery", description: "Explore Mirissa with your dedicated chauffeur — timing flexes around weather, tickets, and your pace." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["colombo-capital-discovery-day", "galle-fort-heritage-day"],
    popular: false,
    publishedAt: "2026-03-09",
    idealFor: "Whale season visitors",
    suggestedVehicleIds: ["sedan", "suv"],
    published: true,
  },
{
    slug: "jaffna-heritage-city-tour",
    title: "Jaffna Heritage City Tour",
    durationDays: 1,
    durationLabel: "4 Hours",
    destinationSlugs: ["nallur-kandaswamy-temple", "jaffna"],
    categoryIds: ["custom-private", "cultural-heritage", "pilgrimage", "photography-tours"],
    vehicleId: "suv",
    startingPriceLkr: null,
    startingPriceUsd: 45,
    highlights: [
      "Nallur Temple",
      "Jaffna Fort",
      "Public Library",
      "Local Market",
      "Rio Ice Cream",
    ],
    travelTips: [
      "Wear modest clothing for temple visits and remove shoes where required.",
      "Carry sun protection — the peninsula can be bright by midday.",
      "Share your hotel pickup point so ferry and city timing stays composed.",
    ],
    bestTimeToVisit: "January to September is generally drier in the north — your Q Pick planner advises the best month for this route.",
    heroGalleryId: "hero-jaffna-heritage-city",
    galleryIds: ["hero-jaffna-heritage-city"],
    catalogSection: "premium-northern",
    seo: {
      title: "Jaffna Heritage City Tour | Premium Private Chauffeur | Quick Pick",
      description: "A 4-hour private Jaffna heritage tour — Nallur Temple, Jaffna Fort, Public Library, local market, and Rio Ice Cream with Q Pick.",
      canonicalPath: "/tours/jaffna-heritage-city-tour",
      ogImage: getTourHeroImageSrc("hero-jaffna-heritage-city"),
      ogTitle: "Jaffna Heritage City Tour | Q Pick",
      twitterTitle: "Jaffna Heritage City Tour",
      twitterDescription: "Nallur Temple, Jaffna Fort, and northern heritage in four private hours.",
      keywords: ["Jaffna tour", "Nallur Temple", "Jaffna Fort", "Northern Sri Lanka", "private chauffeur"],
      intro: "Discover Jaffna's Tamil heritage in a focused four-hour private tour. Your chauffeur guides you from Nallur Kovil's gopuram to Jaffna Fort ramparts, the historic Public Library, a colourful local market stop, and a classic Rio Ice Cream finish.",
    },
    itinerary: [
      {
        day: 1,
        destinationSlug: "nallur-kandaswamy-temple",
        title: "Jaffna heritage circuit",
        description: "Nallur Temple, Jaffna Fort, Public Library, market browsing, and Rio Ice Cream — paced around opening hours and your interests.",
      },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["delft-island-adventure", "nainativu-sacred-island-tour"],
    badge: "new",
    popular: false,
    publishedAt: "2026-03-22",
    idealFor: "Heritage travellers exploring the north",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
{
    slug: "delft-island-adventure",
    title: "Delft Island Adventure",
    durationDays: 1,
    durationLabel: "Full Day",
    destinationSlugs: ["delft-island", "jaffna"],
    categoryIds: ["custom-private", "adventure", "beach-holidays", "photography-tours"],
    vehicleId: "suv",
    startingPriceLkr: null,
    startingPriceUsd: 85,
    highlights: [
      "Ferry Ride",
      "Wild Horses",
      "Baobab Tree",
      "Queen's Tower",
      "Coral Beach",
    ],
    travelTips: [
      "Ferry schedules vary — your chauffeur coordinates the crossing window.",
      "Pack reef-safe sunscreen and water for the open island terrain.",
      "Wear comfortable shoes for sandy paths and historic ruins.",
    ],
    bestTimeToVisit: "Calmer seas are typical January to September — we confirm ferry timing when you request a quote.",
    heroGalleryId: "hero-delft-island-adventure",
    galleryIds: ["hero-delft-island-adventure"],
    catalogSection: "premium-northern",
    seo: {
      title: "Delft Island Adventure | Full-Day Private Tour | Quick Pick",
      description: "A full-day Delft Island adventure — ferry crossing, wild horses, baobab tree, Queen's Tower, and coral beaches with private Q Pick chauffeur.",
      canonicalPath: "/tours/delft-island-adventure",
      ogImage: getTourHeroImageSrc("hero-delft-island-adventure"),
      ogTitle: "Delft Island Adventure | Q Pick",
      twitterTitle: "Delft Island Adventure",
      twitterDescription: "Ferry, wild horses, and coral shores on Delft Island.",
      keywords: ["Delft Island", "Jaffna ferry", "wild horses Sri Lanka", "Northern Sri Lanka tour"],
      intro: "Cross by ferry to remote Delft Island for a full-day adventure. Walk coral beaches, seek out the famous baobab tree and Queen's Tower ruins, watch wild horses on open plains, and return with your private chauffeur handling mainland transfers.",
    },
    itinerary: [
      {
        day: 1,
        destinationSlug: "delft-island",
        title: "Delft Island expedition",
        description: "Ferry crossing, wild horse plains, baobab tree, Queen's Tower, and coral beach time — with mainland transfers by private vehicle.",
      },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["jaffna-heritage-city-tour", "nainativu-sacred-island-tour"],
    badge: "adventure",
    popular: false,
    publishedAt: "2026-03-22",
    idealFor: "Island explorers and photographers",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
{
    slug: "nainativu-sacred-island-tour",
    title: "Nainativu Sacred Island Tour",
    durationDays: 1,
    durationLabel: "6 Hours",
    destinationSlugs: ["nagadeepa-nainativu", "jaffna"],
    categoryIds: ["custom-private", "pilgrimage", "cultural-heritage"],
    vehicleId: "suv",
    startingPriceLkr: null,
    startingPriceUsd: 65,
    highlights: [
      "Nagadeepa Temple",
      "Nagapooshani Amman Temple",
      "Boat Ride",
      "Cultural Experience",
    ],
    travelTips: [
      "Dress modestly for both Buddhist and Hindu sacred sites.",
      "Boat crossings depend on weather — build flexibility into the day.",
      "Carry a light shawl or sarong for temple etiquette.",
    ],
    bestTimeToVisit: "Year-round with seasonal sea conditions — your Q Pick planner confirms boat windows for your dates.",
    heroGalleryId: "hero-nainativu-sacred-island",
    galleryIds: ["hero-nainativu-sacred-island"],
    catalogSection: "premium-northern",
    seo: {
      title: "Nainativu Sacred Island Tour | 6-Hour Private Pilgrimage | Quick Pick",
      description: "A 6-hour Nainativu sacred island tour — Nagadeepa Temple, Nagapooshani Amman Temple, boat ride, and cultural immersion with Q Pick.",
      canonicalPath: "/tours/nainativu-sacred-island-tour",
      ogImage: getTourHeroImageSrc("hero-nainativu-sacred-island"),
      ogTitle: "Nainativu Sacred Island Tour | Q Pick",
      twitterTitle: "Nainativu Sacred Island Tour",
      twitterDescription: "Sacred temples and boat crossings to Nainativu.",
      keywords: ["Nainativu", "Nagadeepa Temple", "Nagapooshani Amman", "Jaffna pilgrimage"],
      intro: "Sail to Nainativu for a six-hour sacred island journey. Visit Nagadeepa Temple and Nagapooshani Amman Kovil, experience the boat crossing, and absorb the blended Buddhist and Hindu heritage of Sri Lanka's northern islands with private chauffeur support on shore.",
    },
    itinerary: [
      {
        day: 1,
        destinationSlug: "nagadeepa-nainativu",
        title: "Nainativu sacred circuit",
        description: "Boat ride to Nainativu, Nagadeepa Temple, Nagapooshani Amman Temple, and cultural time on the island before return.",
      },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport"],
    relatedPackageSlugs: ["jaffna-heritage-city-tour", "delft-island-adventure"],
    popular: false,
    publishedAt: "2026-03-22",
    idealFor: "Pilgrims and cultural travellers",
    suggestedVehicleIds: ["suv", "van"],
    published: true,
  },
];
