import type { TourPackage } from "../types";
import { getTourHeroImageSrc } from "../tour-hero-images";
import { sharedExcluded, sharedIncluded } from "./shared";
import { CATALOG_PACKAGES } from "./catalog";

export { sharedIncluded, sharedExcluded } from "./shared";

export const LEGACY_TOUR_PACKAGES: TourPackage[] = [
  {
    slug: "3-days-cultural-triangle",
    title: "3 Days Cultural Triangle",
    durationDays: 3,
    destinationSlugs: ["negombo", "sigiriya", "dambulla", "anuradhapura", "polonnaruwa"],
    categoryIds: ["popular", "cultural-heritage", "family", "festival", "custom-private"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: [
      "Sigiriya Rock Fortress timed for cooler light",
      "Dambulla Cave Temple murals",
      "Anuradhapura or Polonnaruwa sacred sites",
      "Private Cultural Triangle chauffeur",
    ],
    travelTips: [
      "Wear modest clothing for temple visits and remove shoes where required.",
      "Start Sigiriya early to avoid heat and midday crowds.",
      "Carry cash for ticket counters; connectivity can be uneven inland.",
    ],
    bestTimeToVisit:
      "December to April generally offers drier Cultural Triangle weather. May to September can bring afternoon storms — flexible private pacing helps.",
    heroGalleryId: "hero-cultural-triangle",
    galleryIds: ["hero-cultural-triangle", "sigiriya-hero", "dambulla-hero", "anuradhapura-hero", "polonnaruwa-hero"],
    seo: {
      title: "3 Days Cultural Triangle Private Tour Sri Lanka | Q Pick",
      description:
        "A 3-day private chauffeur tour of Sri Lanka’s Cultural Triangle — Sigiriya, Dambulla, and Anuradhapura or Polonnaruwa with Q Pick.",
      canonicalPath: "/tours/3-days-cultural-triangle",
      ogImage: getTourHeroImageSrc("hero-cultural-triangle"),
      ogTitle: "3 Days Cultural Triangle | Q Pick Private Tours",
      twitterTitle: "3 Days Cultural Triangle Private Tour",
      twitterDescription:
        "Sigiriya, Dambulla and ancient cities with a private Q Pick chauffeur.",
      intro:
        "Three carefully paced days introduce Sri Lanka’s Cultural Triangle without a coach timetable. From the Negombo or Colombo corridor you travel with a dedicated chauffeur to Sigiriya’s rock fortress, Dambulla’s painted caves, and either Anuradhapura’s stupas or Polonnaruwa’s Gal Vihara. Private timing protects cooler climbs and respectful temple visits — ideal as a short heritage escape or the opening chapter of a longer island journey.",
    },
    itinerary: [
      {
        day: 1,
        destinationSlug: "negombo",
        title: "Arrival corridor to the Triangle",
        description:
          "Meet your chauffeur near CMB or Negombo and journey inland. Settle near Sigiriya or Dambulla; evening at leisure.",
      },
      {
        day: 2,
        destinationSlug: "sigiriya",
        title: "Sigiriya & Dambulla",
        description:
          "Climb Sigiriya in softer light, then explore Dambulla Cave Temple. Optional seasonal safari nearby if requested.",
      },
      {
        day: 3,
        destinationSlug: "anuradhapura",
        title: "Ancient city & onward",
        description:
          "Visit Anuradhapura or Polonnaruwa before returning toward Colombo/Negombo or continuing your custom route.",
      },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-airport", "pkg-3d-pace"],
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "14-days-complete-sri-lanka"],
    popular: true,
    published: true,
  },
  {
    slug: "5-days-hill-country-escape",
    title: "5 Days Hill Country Escape",
    durationDays: 5,
    destinationSlugs: ["kandy", "nuwara-eliya", "ella"],
    categoryIds: ["popular", "hill-country-tea", "train-journeys", "honeymoon", "family", "luxury-escapes", "custom-private"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: [
      "Temple of the Tooth in Kandy",
      "Tea plantations around Nuwara Eliya",
      "Nine Arches Bridge in Ella",
      "Optional scenic train segment",
    ],
    travelTips: [
      "Pack a light layer — highland mornings are cooler than the coast.",
      "Confirm train seats in advance if you want the scenic rail stretch.",
      "Bridge viewpoints can be slippery after rain; wear grippy shoes.",
    ],
    bestTimeToVisit:
      "January to April is popular for clearer highland views. The southwest monsoon can bring mist and showers mid-year — still beautiful with flexible photography stops.",
    heroGalleryId: "hero-hill-country-escape",
    galleryIds: ["hero-hill-country-escape", "kandy-hero", "nuwara-eliya-hero", "ella-hero"],
    seo: {
      title: "5 Days Hill Country Escape Private Tour | Ella & Tea Country",
      description:
        "Private 5-day hill country tour through Kandy, Nuwara Eliya tea estates and Ella’s Nine Arches Bridge with Q Pick.",
      canonicalPath: "/tours/5-days-hill-country-escape",
      ogImage: getTourHeroImageSrc("hero-hill-country-escape"),
      ogTitle: "5 Days Hill Country Escape | Q Pick",
      twitterTitle: "Hill Country Escape Private Tour",
      twitterDescription: "Kandy, tea country and Ella with a private chauffeur.",
      intro:
        "Escape into Sri Lanka’s cool highlands on a five-day private journey from Kandy’s Temple of the Tooth to misty tea estates and Ella’s Nine Arches Bridge. Your chauffeur handles winding estate roads while optional train segments can be arranged for the most scenic rail stretch. Designed for couples, families, and travellers who want photography windows without logistical stress.",
    },
    itinerary: [
      {
        day: 1,
        destinationSlug: "kandy",
        title: "To Kandy",
        description:
          "Drive to Kandy via inland routes. Evening lake circuit and Temple of the Tooth timed around rituals.",
      },
      {
        day: 2,
        destinationSlug: "kandy",
        title: "Kandy heritage",
        description:
          "Peradeniya Botanical Gardens, craft streets, and free time for markets or a cultural performance.",
      },
      {
        day: 3,
        destinationSlug: "nuwara-eliya",
        title: "Tea country",
        description:
          "Ascend to Nuwara Eliya for plantation visits, Gregory Lake, and cool-climate leisure.",
      },
      {
        day: 4,
        destinationSlug: "ella",
        title: "Ella viewpoints",
        description:
          "Continue to Ella for Nine Arches Bridge, ridge walks, and highland cafés. Optional train segment.",
      },
      {
        day: 5,
        destinationSlug: "colombo",
        title: "Descent or coast link",
        description:
          "Depart toward Colombo, the southern coast, or your next custom destination with luggage handled by road.",
      },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "pkg-5d-train", "pkg-5d-weather"],
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "10-days-wildlife-adventure"],
    popular: true,
    published: true,
  },
  {
    slug: "7-days-best-of-sri-lanka",
    title: "7 Days Best of Sri Lanka",
    durationDays: 7,
    destinationSlugs: ["colombo", "sigiriya", "dambulla", "kandy", "ella", "galle", "mirissa"],
    categoryIds: ["popular", "cultural-heritage", "beach-holidays", "hill-country-tea", "honeymoon", "family", "luxury-escapes", "food", "custom-private"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: [
      "Cultural Triangle icons",
      "Kandy and highland tea country",
      "Ella scenic landmarks",
      "Southern coast at Galle or Mirissa",
    ],
    travelTips: [
      "Balance temple days with coastal downtime — seven days move quickly.",
      "Keep one flexible half-day for weather or photography.",
      "Ask us to connect CMB pickup via airport transfer if arriving international.",
    ],
    bestTimeToVisit:
      "December to March suits west and south coasts plus highland travel. For east-coast add-ons, consider May to September and ask us to adjust the finish.",
    heroGalleryId: "hero-best-of-sri-lanka",
    galleryIds: ["hero-best-of-sri-lanka", "sigiriya-hero", "kandy-hero", "ella-hero", "galle-hero", "mirissa-hero"],
    seo: {
      title: "7 Days Best of Sri Lanka Private Tour Package | Q Pick",
      description:
        "See Sigiriya, Kandy, Ella and the southern coast on Q Pick’s 7-day Best of Sri Lanka private chauffeur tour.",
      canonicalPath: "/tours/7-days-best-of-sri-lanka",
      ogImage: getTourHeroImageSrc("hero-best-of-sri-lanka"),
      ogTitle: "7 Days Best of Sri Lanka | Q Pick",
      twitterTitle: "Best of Sri Lanka 7-Day Private Tour",
      twitterDescription: "Culture, highlands and coast with a private chauffeur.",
      intro:
        "Seven days is Q Pick’s signature overview for first-time visitors who want culture, highlands, and beach in one composed week. Travel privately from Colombo or the airport corridor to Sigiriya and Dambulla, onward through Kandy and Ella, then finish on the southern coast at Galle Fort or Mirissa. Unlike rigid group coaches, this itinerary flexes for sunrise climbs, bridge photography, and unhurried fort walks.",
    },
    itinerary: [
      { day: 1,
        destinationSlug: "colombo", title: "Arrival", description: "Airport meet and transfer to Colombo or Negombo; briefing with your chauffeur." },
      { day: 2,
        destinationSlug: "sigiriya", title: "Cultural Triangle", description: "Journey to Sigiriya / Dambulla for fortress or cave temple time." },
      { day: 3,
        destinationSlug: "kandy", title: "Heritage to Kandy", description: "Complete Triangle highlights, then continue to Kandy." },
      { day: 4,
        destinationSlug: "nuwara-eliya", title: "Highlands", description: "Scenic drive into tea country toward Nuwara Eliya or Ella." },
      { day: 5,
        destinationSlug: "ella", title: "Ella", description: "Nine Arches Bridge, viewpoints, and café leisure." },
      { day: 6,
        destinationSlug: "galle", title: "Southern coast", description: "Descend to Galle Fort and Mirissa for sunset and seaside dining." },
      { day: 7,
        destinationSlug: "mirissa", title: "Departure", description: "Coastal morning at leisure and private transfer to CMB or Colombo." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-group", "pkg-7d-fitness"],
    relatedPackageSlugs: ["5-days-hill-country-escape", "10-days-wildlife-adventure", "14-days-complete-sri-lanka"],
    popular: true,
    published: true,
  },
  {
    slug: "10-days-wildlife-adventure",
    title: "10 Days Wildlife Adventure",
    durationDays: 10,
    destinationSlugs: ["colombo", "sigiriya", "kandy", "nuwara-eliya", "ella", "yala", "mirissa", "galle"],
    categoryIds: ["popular", "wildlife-safari", "adventure", "hill-country-tea", "luxury-escapes", "custom-private"],
    vehicleId: "suv",
    startingPriceLkr: null,
    highlights: [
      "Heritage warm-up in the Cultural Triangle",
      "Highland tea country & Ella",
      "Yala leopard safari window",
      "Southern coast recovery days",
    ],
    travelTips: [
      "Safari sightings are never guaranteed — build patience into the day.",
      "Park jeep fees are separate; we coordinate timing after your request.",
      "Carry binoculars and muted clothing for game drives.",
    ],
    bestTimeToVisit:
      "February to July is often strong for Yala wildlife viewing, while coastal finishes remain pleasant in the first quarter. We refine park choice to season when you request a quote.",
    heroGalleryId: "hero-wildlife-adventure",
    galleryIds: ["hero-wildlife-adventure", "sigiriya-hero", "ella-hero", "yala-hero", "mirissa-hero", "galle-hero"],
    seo: {
      title: "10 Days Wildlife Adventure Private Tour Sri Lanka | Q Pick",
      description:
        "A 10-day private Sri Lanka wildlife adventure — Cultural Triangle, hill country, Yala safari logistics and southern beaches with Q Pick.",
      canonicalPath: "/tours/10-days-wildlife-adventure",
      ogImage: getTourHeroImageSrc("hero-wildlife-adventure"),
      ogTitle: "10 Days Wildlife Adventure | Q Pick",
      twitterTitle: "Wildlife Adventure Private Tour",
      twitterDescription: "Yala safari window with heritage and coast, privately chauffeured.",
      intro:
        "Ten days weave heritage and highlands into Sri Lanka’s premier leopard landscape. After Sigiriya and tea country, your private chauffeur positions you for a Yala safari window, then softens the finish along Mirissa and Galle. Built for travellers who want wildlife without abandoning the island’s cultural and coastal icons — with jeep fees arranged as clear add-ons after review.",
    },
    itinerary: [
      { day: 1,
        destinationSlug: "colombo", title: "Arrival", description: "CMB meet and city or Negombo settle-in." },
      { day: 2,
        destinationSlug: "sigiriya", title: "Sigiriya region", description: "Rock fortress and Triangle immersion." },
      { day: 3,
        destinationSlug: "kandy", title: "Kandy", description: "Temple of the Tooth and highland approach." },
      { day: 4,
        destinationSlug: "nuwara-eliya", title: "Tea country", description: "Nuwara Eliya plantations and cool climate." },
      { day: 5,
        destinationSlug: "ella", title: "Ella", description: "Nine Arches and ridge walks." },
      { day: 6,
        destinationSlug: "yala", title: "Toward Yala", description: "Scenic descent to the southeast wildlife belt." },
      { day: 7,
        destinationSlug: "yala", title: "Safari day", description: "Yala National Park jeep safari (park fees extra)." },
      { day: 8,
        destinationSlug: "mirissa", title: "Southern beaches", description: "Mirissa Coconut Tree Hill and coastal downtime." },
      { day: 9,
        destinationSlug: "galle", title: "Galle Fort", description: "Ramparts, lighthouse, and boutique exploration." },
      { day: 10,
        destinationSlug: "colombo", title: "Departure", description: "Private transfer to CMB or Colombo." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-price", "hub-group", "pkg-10d-safari"],
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "14-days-complete-sri-lanka", "21-days-grand-explorer"],
    popular: true,
    published: true,
  },
  {
    slug: "14-days-complete-sri-lanka",
    title: "14 Days Complete Sri Lanka",
    durationDays: 14,
    destinationSlugs: [
      "negombo",
      "anuradhapura",
      "sigiriya",
      "polonnaruwa",
      "dambulla",
      "kandy",
      "nuwara-eliya",
      "ella",
      "yala",
      "mirissa",
      "galle",
      "bentota",
      "trincomalee",
      "colombo",
    ],
    categoryIds: ["popular", "cultural-heritage", "wildlife-safari", "beach-holidays", "hill-country-tea", "family", "train-journeys", "custom-private"],
    vehicleId: "van",
    startingPriceLkr: null,
    highlights: [
      "Full Cultural Triangle depth",
      "Hill country and southern safari",
      "West and east coast options",
      "Family-ready pacing",
    ],
    travelTips: [
      "Fourteen days still benefit from one rest half-day mid-circuit.",
      "East-coast chapters depend on season — we advise when you book.",
      "A van suits families with more luggage across long routes.",
    ],
    bestTimeToVisit:
      "Shoulder months and December–March work well for west/south focus. For Nilaveli or other east finishes, May–September is often kinder — we route accordingly.",
    heroGalleryId: "hero-complete-sri-lanka",
    galleryIds: [
      "hero-complete-sri-lanka",
      "anuradhapura-hero",
      "sigiriya-hero",
      "ella-hero",
      "yala-hero",
      "trincomalee-hero",
      "galle-hero",
    ],
    seo: {
      title: "14 Days Complete Sri Lanka Private Tour | Island Circuit",
      description:
        "A complete 14-day private Sri Lanka tour covering Cultural Triangle, tea country, Yala, southern beaches and seasonal east-coast options.",
      canonicalPath: "/tours/14-days-complete-sri-lanka",
      ogImage: getTourHeroImageSrc("hero-complete-sri-lanka"),
      ogTitle: "14 Days Complete Sri Lanka | Q Pick",
      twitterTitle: "Complete Sri Lanka 14-Day Private Tour",
      twitterDescription: "Heritage, highlands, wildlife and coast with private chauffeur.",
      intro:
        "Fourteen days unlock a complete private circuit: ancient cities, tea highlands, leopard country, and both coastal moods when season allows. This itinerary deepens the Cultural Triangle, keeps Ella and Nuwara Eliya unhurried, adds Yala logistics, and finishes with southern beaches plus an optional Trincomalee or Colombo chapter. Built for families and curious travellers who dislike skipping icons.",
    },
    itinerary: [
      { day: 1,
        destinationSlug: "negombo", title: "Arrival Negombo", description: "CMB pickup and west-coast settle-in." },
      { day: 2,
        destinationSlug: "anuradhapura", title: "Anuradhapura", description: "Sacred city stupas and archaeological park." },
      { day: 3,
        destinationSlug: "sigiriya", title: "Sigiriya", description: "Rock fortress and Triangle base." },
      { day: 4,
        destinationSlug: "polonnaruwa", title: "Polonnaruwa", description: "Medieval capital and optional elephant park." },
      { day: 5,
        destinationSlug: "dambulla", title: "Dambulla to Kandy", description: "Cave temple and highland capital." },
      { day: 6,
        destinationSlug: "kandy", title: "Kandy", description: "Temple of the Tooth and gardens." },
      { day: 7,
        destinationSlug: "nuwara-eliya", title: "Nuwara Eliya", description: "Tea estates and cool climate." },
      { day: 8,
        destinationSlug: "ella", title: "Ella", description: "Nine Arches and viewpoints." },
      { day: 9,
        destinationSlug: "yala", title: "Yala approach", description: "Southeast wildlife belt transfer." },
      { day: 10,
        destinationSlug: "yala", title: "Safari", description: "Yala National Park jeep day." },
      { day: 11,
        destinationSlug: "mirissa", title: "Mirissa", description: "Southern beach recovery day." },
      { day: 12,
        destinationSlug: "galle", title: "Galle", description: "Fort heritage and coast." },
      { day: 13,
        destinationSlug: "trincomalee", title: "East or southwest", description: "Trincomalee season option or Bentota buffer." },
      { day: 14,
        destinationSlug: "colombo", title: "Colombo departure", description: "City buffer and CMB transfer." },
    ],
    included: sharedIncluded,
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "hub-payment", "pkg-14d-pace"],
    relatedPackageSlugs: ["10-days-wildlife-adventure", "21-days-grand-explorer", "7-days-best-of-sri-lanka"],
    popular: true,
    published: true,
  },
  {
    slug: "21-days-grand-explorer",
    title: "21 Days Grand Explorer",
    durationDays: 21,
    destinationSlugs: [
      "colombo",
      "negombo",
      "anuradhapura",
      "sigiriya",
      "polonnaruwa",
      "dambulla",
      "kandy",
      "nuwara-eliya",
      "ella",
      "yala",
      "mirissa",
      "galle",
      "bentota",
      "trincomalee",
      "arugam-bay",
    ],
    categoryIds: [
      "popular",
      "cultural-heritage",
      "wildlife-safari",
      "beach-holidays",
      "hill-country-tea",
      "honeymoon",
      "family",
      "adventure",
      "luxury-escapes",
      "train-journeys",
      "ayurveda-wellness",
      "food",
      "festival",
      "custom-private",
    ],
    vehicleId: "van",
    startingPriceLkr: null,
    highlights: [
      "Full-island seasonal routing",
      "Deep heritage and wildlife time",
      "East and west coast beaches",
      "Ultimate private chauffeur pace",
    ],
    travelTips: [
      "Twenty-one days should follow the dry side of the island when possible.",
      "Build buffer nights after long cross-island drives.",
      "Tell us surf, snorkel, or temple priorities so we weight the east vs south.",
    ],
    bestTimeToVisit:
      "A grand circuit can chase dry weather: west/south in December–March, east around May–September. We confirm the sequence when you share travel months.",
    heroGalleryId: "hero-grand-explorer",
    galleryIds: [
      "hero-grand-explorer",
      "sigiriya-hero",
      "ella-hero",
      "yala-hero",
      "mirissa-hero",
      "trincomalee-hero",
      "arugam-bay-hero",
    ],
    seo: {
      title: "21 Days Grand Explorer Sri Lanka Private Tour | Q Pick",
      description:
        "The 21-day Grand Explorer private tour of Sri Lanka — heritage, highlands, wildlife, and both coasts with a dedicated Q Pick chauffeur.",
      canonicalPath: "/tours/21-days-grand-explorer",
      ogImage: getTourHeroImageSrc("hero-grand-explorer"),
      ogTitle: "21 Days Grand Explorer | Q Pick",
      twitterTitle: "Grand Explorer 21-Day Private Tour",
      twitterDescription: "Full-island private chauffeur journey across Sri Lanka.",
      intro:
        "Twenty-one days is Q Pick’s Grand Explorer standard for travellers who refuse to choose between coasts, kingdoms, and wildlife. This private chauffeur odyssey weaves the Cultural Triangle, Kandy and tea country, Yala safaris, southern beaches, and east-coast chapters such as Trincomalee or Arugam Bay according to season. Couples stretch romantic stays; families add buffer days; photographers linger at Nine Arches and Nilaveli.",
    },
    itinerary: [
      { day: 1,
        destinationSlug: "negombo", title: "Arrival", description: "CMB to Negombo or Colombo." },
      { day: 2,
        destinationSlug: "colombo", title: "West coast buffer", description: "Lagoon or city leisure." },
      { day: 3,
        destinationSlug: "anuradhapura", title: "Anuradhapura", description: "Sacred city immersion." },
      { day: 4,
        destinationSlug: "anuradhapura", title: "Northwest option", description: "Optional wildlife or rest day." },
      { day: 5,
        destinationSlug: "sigiriya", title: "Sigiriya", description: "Rock fortress focus." },
      { day: 6,
        destinationSlug: "polonnaruwa", title: "Polonnaruwa", description: "Medieval ruins and lakes." },
      { day: 7,
        destinationSlug: "dambulla", title: "Dambulla", description: "Cave temple and village culture." },
      { day: 8,
        destinationSlug: "kandy", title: "Kandy", description: "Temple of the Tooth." },
      { day: 9,
        destinationSlug: "kandy", title: "Kandy leisure", description: "Gardens and crafts." },
      { day: 10,
        destinationSlug: "nuwara-eliya", title: "Nuwara Eliya", description: "Tea country." },
      { day: 11,
        destinationSlug: "nuwara-eliya", title: "Estates", description: "Optional plateau or plantation day." },
      { day: 12,
        destinationSlug: "ella", title: "Ella", description: "Nine Arches and ridges." },
      { day: 13,
        destinationSlug: "ella", title: "Ella leisure", description: "Cafés and short walks." },
      { day: 14,
        destinationSlug: "yala", title: "Yala", description: "Wildlife approach." },
      { day: 15,
        destinationSlug: "yala", title: "Safari", description: "Park jeep day." },
      { day: 16,
        destinationSlug: "mirissa", title: "Mirissa", description: "Southern ocean." },
      { day: 17,
        destinationSlug: "galle", title: "Galle", description: "Fort heritage and coast." },
      { day: 18,
        destinationSlug: "bentota", title: "Bentota", description: "Southwest resort pace." },
      { day: 19,
        destinationSlug: "trincomalee", title: "East coast", description: "Trincomalee or Arugam Bay by season." },
      { day: 20,
        destinationSlug: "arugam-bay", title: "East leisure", description: "Beach and water time." },
      { day: 21,
        destinationSlug: "colombo", title: "Return & depart", description: "Cross-island transfer to CMB." },
    ],
    included: [
      ...sharedIncluded,
      "Extended itinerary planning support",
      "Seasonal routing advice (east vs west)",
    ],
    excluded: sharedExcluded,
    faqIds: ["hub-customize", "hub-price", "pkg-21d-season"],
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "10-days-wildlife-adventure"],
    popular: true,
    published: true,
  },
];

export const TOUR_PACKAGES: TourPackage[] = [
  ...LEGACY_TOUR_PACKAGES,
  ...CATALOG_PACKAGES,
];
