import type { TourDestination } from "../types";

const D = "/images/destinations";

export const TOUR_DESTINATIONS: TourDestination[] = [
  {
    slug: "negombo",
    name: "Negombo",
    region: "West Coast",
    province: "Western Province",
    description:
      "Negombo sits minutes from Bandaranaike International Airport, where lagoon canals, a long sandy beach, and a working fishing harbour introduce Sri Lanka at an easy pace.",
    highlights: ["Negombo Beach", "Lagoon canals", "Fishing harbour"],
    thingsToDo: ["Beach walk at sunset", "Lagoon boat ride", "Seafood dinner"],
    nearbyAttractions: ["Muthurajawela wetlands", "Dutch Fort remnant", "Fish market"],
    keywords: ["Negombo Beach", "CMB airport Negombo"],
    imageSrc: `${D}/negombo.webp`,
    imageAlt: "Traditional Oruwa canoe on Negombo Beach with palm trees",
    lat: 7.2083,
    lng: 79.8358,
    driveFromColomboHours: 1.2,
    driveFromColomboLabel: "~1–1.5 hrs from Colombo",
    bestSeason: "Dec–Mar (drier west)",
    weatherLabel: "Warm coastal · 27–32°C typical",
    bestPhotoTime: "Golden hour on the beach",
    unesco: false,
    relatedPackageSlugs: ["3-days-cultural-triangle", "14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "colombo",
    name: "Colombo",
    region: "Western Province",
    province: "Western Province",
    description:
      "Colombo blends colonial streets, the Lotus Tower skyline, and the ocean promenade at Galle Face — the capital gateway before countryside chapters begin.",
    highlights: ["Lotus Tower", "Galle Face Green", "City temples"],
    thingsToDo: ["Galle Face stroll", "Independence Square", "Cinnamon Gardens"],
    nearbyAttractions: ["Gangaramaya Temple", "Beira Lake", "Old Parliament"],
    keywords: ["Colombo Lotus Tower", "Galle Face"],
    imageSrc: `${D}/colombo.webp`,
    imageAlt: "Colombo skyline with Lotus Tower above Beira Lake",
    lat: 6.9271,
    lng: 79.8612,
    driveFromColomboHours: 0,
    driveFromColomboLabel: "City centre",
    bestSeason: "Year-round gateway",
    weatherLabel: "Humid coastal · 26–32°C",
    bestPhotoTime: "Blue hour at Lotus Tower",
    unesco: false,
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "10-days-wildlife-adventure", "14-days-complete-sri-lanka"],
  },
  {
    slug: "sigiriya",
    name: "Sigiriya",
    region: "Cultural Triangle",
    province: "Central Province",
    description:
      "Sigiriya Rock Fortress rises from dry-zone jungle as one of Sri Lanka’s most recognisable UNESCO landmarks — frescoes, water gardens, and a summit palace.",
    highlights: ["Rock Fortress", "Water gardens", "Mirror Wall"],
    thingsToDo: ["Sunrise climb", "Garden walk", "Village lunch"],
    nearbyAttractions: ["Pidurangala Rock", "Minneriya (seasonal)", "Dambulla caves"],
    keywords: ["Sigiriya Rock Fortress", "UNESCO"],
    imageSrc: `${D}/sigiriya.webp`,
    imageAlt: "Sigiriya Rock Fortress rising above tropical forest",
    lat: 7.957,
    lng: 80.7603,
    driveFromColomboHours: 4,
    driveFromColomboLabel: "~3.5–4.5 hrs from Colombo",
    bestSeason: "Dec–Apr (drier Triangle)",
    weatherLabel: "Hot dry-zone · start early",
    bestPhotoTime: "Soft morning light on the rock",
    unesco: true,
    relatedPackageSlugs: ["3-days-cultural-triangle", "7-days-best-of-sri-lanka", "14-days-complete-sri-lanka"],
  },
  {
    slug: "dambulla",
    name: "Dambulla",
    region: "Cultural Triangle",
    province: "Central Province",
    description:
      "Dambulla Cave Temple shelters centuries of Buddhist murals and statues inside a natural rock monastery — a contemplative counterpoint to Sigiriya.",
    highlights: ["Cave murals", "Golden Temple", "Hilltop panorama"],
    thingsToDo: ["Cave temple visit", "Market stop", "Viewpoint photos"],
    nearbyAttractions: ["Sigiriya", "Namal Uyana", "Village crafts"],
    keywords: ["Dambulla Cave Temple", "UNESCO"],
    imageSrc: `${D}/dambulla.webp`,
    imageAlt: "Buddha statues inside Dambulla Cave Temple",
    lat: 7.8567,
    lng: 80.6492,
    driveFromColomboHours: 3.5,
    driveFromColomboLabel: "~3–4 hrs from Colombo",
    bestSeason: "Dec–Apr",
    weatherLabel: "Warm inland · shaded caves",
    bestPhotoTime: "Late morning murals (no flash)",
    unesco: true,
    relatedPackageSlugs: ["3-days-cultural-triangle", "7-days-best-of-sri-lanka"],
  },
  {
    slug: "kandy",
    name: "Kandy",
    region: "Central Highlands",
    province: "Central Province",
    description:
      "Kandy, the last royal capital, wraps around a lake beneath forested hills. The Temple of the Tooth remains the spiritual heart of the city.",
    highlights: ["Temple of the Tooth", "Kandy Lake", "Peradeniya Gardens"],
    thingsToDo: ["Temple visit", "Lake walk", "Botanical gardens"],
    nearbyAttractions: ["Udawatta Kele", "Arts & crafts lane", "Bahirawakanda"],
    keywords: ["Temple of the Tooth Kandy"],
    imageSrc: `${D}/kandy.webp`,
    imageAlt: "Temple of the Sacred Tooth Relic in Kandy",
    lat: 7.2906,
    lng: 80.6337,
    driveFromColomboHours: 3,
    driveFromColomboLabel: "~3–3.5 hrs from Colombo",
    bestSeason: "Jan–Apr · cooler evenings",
    weatherLabel: "Mild highland edge · 22–28°C",
    bestPhotoTime: "Evening lights on the lake",
    unesco: true,
    relatedPackageSlugs: ["5-days-hill-country-escape", "7-days-best-of-sri-lanka", "10-days-wildlife-adventure"],
  },
  {
    slug: "nuwara-eliya",
    name: "Nuwara Eliya",
    region: "Tea Country",
    province: "Central Province",
    description:
      "Nuwara Eliya sits high in Sri Lanka’s tea belt — cool air, terraced plantations, and Gregory Lake for misty highland mornings.",
    highlights: ["Tea plantations", "Gregory Lake", "Cool climate"],
    thingsToDo: ["Tea factory visit", "Lake stroll", "Viewpoint drive"],
    nearbyAttractions: ["Hakgala Gardens", "Mackwoods Tea", "Horton Plains (day trip)"],
    keywords: ["Nuwara Eliya tea"],
    imageSrc: `${D}/nuwara-eliya.webp`,
    imageAlt: "Terraced tea plantations near Nuwara Eliya",
    lat: 6.9497,
    lng: 80.7891,
    driveFromColomboHours: 5,
    driveFromColomboLabel: "~5–6 hrs from Colombo",
    bestSeason: "Jan–Mar · clear mornings",
    weatherLabel: "Cool misty · 12–22°C",
    bestPhotoTime: "Soft morning plantation light",
    unesco: false,
    relatedPackageSlugs: ["5-days-hill-country-escape", "7-days-best-of-sri-lanka"],
  },
  {
    slug: "ella",
    name: "Ella",
    region: "Uva Highlands",
    province: "Uva Province",
    description:
      "Ella is the photogenic heart of the hill country — Nine Arches Bridge, ridge walks, and café terraces above tea valleys.",
    highlights: ["Nine Arches Bridge", "Little Adam’s Peak", "Tea valleys"],
    thingsToDo: ["Bridge viewpoint", "Short ridge walk", "Scenic train option"],
    nearbyAttractions: ["Ravana Falls", "Demodara Loop", "Ella Rock"],
    keywords: ["Nine Arches Bridge Ella"],
    imageSrc: `${D}/ella.webp`,
    imageAlt: "Nine Arches Bridge in Ella with a blue train",
    lat: 6.8667,
    lng: 81.0466,
    driveFromColomboHours: 6,
    driveFromColomboLabel: "~6–7 hrs from Colombo",
    bestSeason: "Jan–Apr · misty drama year-round",
    weatherLabel: "Cool highland · pack a layer",
    bestPhotoTime: "Golden hour at Nine Arches",
    unesco: false,
    relatedPackageSlugs: ["5-days-hill-country-escape", "7-days-best-of-sri-lanka", "14-days-complete-sri-lanka"],
  },
  {
    slug: "yala",
    name: "Yala",
    region: "Southeast Wildlife",
    province: "Southern / Uva",
    description:
      "Yala National Park is Sri Lanka’s best-known leopard landscape — scrub jungle, rock outcrops, and lagoons shared by elephants and rich birdlife.",
    highlights: ["Leopard safari", "Elephants", "Dry-zone lagoons"],
    thingsToDo: ["Dawn jeep safari", "Birdwatching", "Park gate timing"],
    nearbyAttractions: ["Kataragama", "Sithulpawwa", "Coastal lagoons"],
    keywords: ["Yala leopard safari"],
    imageSrc: `${D}/yala.webp`,
    imageAlt: "Sri Lankan leopard at a waterhole in Yala National Park",
    lat: 6.3725,
    lng: 81.5185,
    driveFromColomboHours: 5.5,
    driveFromColomboLabel: "~5–6 hrs from Colombo",
    bestSeason: "Feb–Jul often strong for wildlife",
    weatherLabel: "Hot dry-zone · hydrated days",
    bestPhotoTime: "First light on game drives",
    unesco: false,
    relatedPackageSlugs: ["10-days-wildlife-adventure", "14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "galle",
    name: "Galle",
    region: "Southern Coast",
    province: "Southern Province",
    description:
      "Galle Fort is a living Dutch colonial enclave on the southern shore — lighthouse, ocean ramparts, and boutique streets.",
    highlights: ["Fort Lighthouse", "Rampart walks", "Old town"],
    thingsToDo: ["Rampart sunset", "Fort cafés", "Lighthouse photos"],
    nearbyAttractions: ["Unawatuna", "Jungle Beach", "Dutch Hospital"],
    keywords: ["Galle Fort", "UNESCO"],
    imageSrc: `${D}/galle.webp`,
    imageAlt: "Galle Fort Lighthouse on Dutch ramparts",
    lat: 6.0329,
    lng: 80.2168,
    driveFromColomboHours: 2.5,
    driveFromColomboLabel: "~2–3 hrs from Colombo",
    bestSeason: "Dec–Mar (southwest)",
    weatherLabel: "Warm coastal · sea breeze",
    bestPhotoTime: "Sunset on the ramparts",
    unesco: true,
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "10-days-wildlife-adventure", "14-days-complete-sri-lanka"],
  },
  {
    slug: "mirissa",
    name: "Mirissa",
    region: "Southern Coast",
    province: "Southern Province",
    description:
      "Mirissa is known for Coconut Tree Hill sunsets, a crescent bay, and seasonal whale-watching — a soft landing after highlands or wildlife.",
    highlights: ["Coconut Tree Hill", "Bay beach", "Whale season"],
    thingsToDo: ["Hill sunset", "Beach day", "Seasonal whale boat"],
    nearbyAttractions: ["Weligama", "Secret Beach", "Parrot Rock"],
    keywords: ["Coconut Tree Hill Mirissa"],
    imageSrc: `${D}/mirissa.webp`,
    imageAlt: "Coconut Tree Hill palms overlooking Mirissa ocean",
    lat: 5.9483,
    lng: 80.4719,
    driveFromColomboHours: 3,
    driveFromColomboLabel: "~3–3.5 hrs from Colombo",
    bestSeason: "Dec–Apr · whales often Nov–Apr",
    weatherLabel: "Warm tropical · ocean air",
    bestPhotoTime: "Sunset at Coconut Tree Hill",
    unesco: false,
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "10-days-wildlife-adventure"],
  },
  {
    slug: "bentota",
    name: "Bentota",
    region: "Southwest Coast",
    province: "Southern Province",
    description:
      "Bentota offers a wide golden beach and lagoon waterways along the southwest corridor between Colombo and Galle.",
    highlights: ["Bentota Beach", "Lagoon", "Resort calm"],
    thingsToDo: ["Beach day", "Lagoon boat", "River mouth walks"],
    nearbyAttractions: ["Brief Garden", "Kosgoda turtle hatchery", "Madu River"],
    keywords: ["Bentota Beach"],
    imageSrc: `${D}/bentota.webp`,
    imageAlt: "Aerial Bentota Beach with turquoise ocean",
    lat: 6.421,
    lng: 79.9959,
    driveFromColomboHours: 1.5,
    driveFromColomboLabel: "~1.5–2 hrs from Colombo",
    bestSeason: "Dec–Mar",
    weatherLabel: "Warm coastal · resort breeze",
    bestPhotoTime: "Midday turquoise beach tones",
    unesco: false,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "trincomalee",
    name: "Trincomalee",
    region: "Eastern Coast",
    province: "Eastern Province",
    description:
      "Trincomalee and nearby Nilaveli open onto clear east-coast water, with snorkelling around Pigeon Island in season.",
    highlights: ["Nilaveli Beach", "Pigeon Island", "Harbour temples"],
    thingsToDo: ["Nilaveli swim", "Seasonal snorkel", "Koneswaram Temple"],
    nearbyAttractions: ["Pigeon Island", "Fort Frederick", "Marble Beach"],
    keywords: ["Nilaveli Beach"],
    imageSrc: `${D}/trincomalee.webp`,
    imageAlt: "Quiet shoreline near Trincomalee and Nilaveli",
    lat: 8.5874,
    lng: 81.2152,
    driveFromColomboHours: 6.5,
    driveFromColomboLabel: "~6–7 hrs from Colombo",
    bestSeason: "May–Sep (east coast)",
    weatherLabel: "Warm clear · seasonal calm seas",
    bestPhotoTime: "Morning Nilaveli turquoise",
    unesco: false,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "anuradhapura",
    name: "Anuradhapura",
    region: "Cultural Triangle",
    province: "North Central Province",
    description:
      "Anuradhapura is Sri Lanka’s ancient sacred city — monumental stupas including Ruwanwelisaya, monastic ruins, and quiet lakes.",
    highlights: ["Ruwanwelisaya", "Sacred Bodhi", "Ancient reservoirs"],
    thingsToDo: ["Stupa circuit", "Bike the park", "Lake evening"],
    nearbyAttractions: ["Mihintale", "Isurumuniya", "Abhayagiri"],
    keywords: ["Ruwanwelisaya", "UNESCO"],
    imageSrc: `${D}/anuradhapura.webp`,
    imageAlt: "Ruwanwelisaya stupa in Anuradhapura",
    lat: 8.3114,
    lng: 80.4037,
    driveFromColomboHours: 4.5,
    driveFromColomboLabel: "~4–5 hrs from Colombo",
    bestSeason: "Dec–Apr",
    weatherLabel: "Hot dry-zone · modest dress",
    bestPhotoTime: "Soft light on white dagobas",
    unesco: true,
    relatedPackageSlugs: ["3-days-cultural-triangle", "14-days-complete-sri-lanka"],
  },
  {
    slug: "polonnaruwa",
    name: "Polonnaruwa",
    region: "Cultural Triangle",
    province: "North Central Province",
    description:
      "Polonnaruwa preserves Sri Lanka’s medieval capital among lakes and woodland — from the Vatadage to Gal Vihara’s rock-cut Buddhas.",
    highlights: ["Gal Vihara", "Vatadage", "Royal ruins"],
    thingsToDo: ["Gal Vihara", "Cycle the ruins", "Lake views"],
    nearbyAttractions: ["Parakrama Samudra", "Rankoth Vehera", "Minneriya (seasonal)"],
    keywords: ["Gal Vihara", "UNESCO"],
    imageSrc: `${D}/polonnaruwa.webp`,
    imageAlt: "Ancient Polonnaruwa stone shrine with Buddha statue",
    lat: 7.9403,
    lng: 81.0188,
    driveFromColomboHours: 5,
    driveFromColomboLabel: "~5–5.5 hrs from Colombo",
    bestSeason: "Dec–Apr",
    weatherLabel: "Hot inland · shade between sites",
    bestPhotoTime: "Morning at Gal Vihara",
    unesco: true,
    relatedPackageSlugs: ["3-days-cultural-triangle", "14-days-complete-sri-lanka"],
  },
  {
    slug: "arugam-bay",
    name: "Arugam Bay",
    region: "Eastern Coast",
    province: "Eastern Province",
    description:
      "Arugam Bay is Sri Lanka’s celebrated east-coast surf town — long right-hand breaks and a relaxed beach village rhythm.",
    highlights: ["Surf breaks", "Beach evenings", "Lagoons"],
    thingsToDo: ["Surf session", "Lagoon sunset", "Beach cafés"],
    nearbyAttractions: ["Pottuvil lagoon", "Kudumbigala", "Panama beaches"],
    keywords: ["Arugam Bay surfing"],
    imageSrc: `${D}/arugam-bay.webp`,
    imageAlt: "Surfer riding a turquoise wave at Arugam Bay",
    lat: 6.8404,
    lng: 81.836,
    driveFromColomboHours: 7,
    driveFromColomboLabel: "~7–8 hrs from Colombo",
    bestSeason: "Apr–Oct (surf season peaks mid-year)",
    weatherLabel: "Warm coastal · east-season seas",
    bestPhotoTime: "Morning barrels · sunset lagoon",
    unesco: false,
    relatedPackageSlugs: ["21-days-grand-explorer"],
  },
];
