import type { TourDestination } from "../types";
import { getDestinationImageSrc } from "@/lib/destination-image-catalog";

const img = getDestinationImageSrc;

export const TOUR_DESTINATIONS: TourDestination[] = [
  {
    slug: "negombo",
    name: "Negombo",
    region: "West Coast",
    province: "Western Province",
    description:
      "Negombo sits minutes from Bandaranaike International Airport, where lagoon canals, a long sandy beach, and a working fishing harbour introduce Sri Lanka at an easy pace.",
    highlights: ["Negombo Beach", "Lagoon canals", "Fishing harbour"],
    thingsToDo: ["Beach walk at sunset", "Lagoon boat ride", "Seafood dinner"],
    nearbyAttractions: ["Muthurajawela wetlands", "Dutch Fort remnant", "Fish market"],
    keywords: ["Negombo Beach", "CMB airport Negombo"],
    imageSrc: img("negombo"),
    imageAlt: "Traditional Oruwa canoe on Negombo Beach with palm trees",
    lat: 7.2083,
    lng: 79.8358,
    driveFromColomboHours: 1.2,
    driveFromColomboLabel: "~1–1.5 hrs from Colombo",
    bestSeason: "Dec–Mar (drier west)",
    weatherLabel: "Warm coastal · 27–32°C typical",
    bestPhotoTime: "Golden hour on the beach",
    unesco: false,
    relatedPackageSlugs: ["3-days-cultural-triangle", "14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "colombo",
    name: "Colombo",
    region: "Western Province",
    province: "Western Province",
    description:
      "Colombo blends colonial streets, the Lotus Tower skyline, and the ocean promenade at Galle Face — the capital gateway before countryside chapters begin.",
    highlights: ["Lotus Tower", "Galle Face Green", "City temples"],
    thingsToDo: ["Galle Face stroll", "Independence Square", "Cinnamon Gardens"],
    nearbyAttractions: ["Gangaramaya Temple", "Beira Lake", "Old Parliament"],
    keywords: ["Colombo Lotus Tower", "Galle Face"],
    imageSrc: img("colombo"),
    imageAlt: "Colombo skyline with Lotus Tower above Beira Lake",
    lat: 6.9271,
    lng: 79.8612,
    driveFromColomboHours: 0,
    driveFromColomboLabel: "City centre",
    bestSeason: "Year-round gateway",
    weatherLabel: "Humid coastal · 26–32°C",
    bestPhotoTime: "Blue hour at Lotus Tower",
    unesco: false,
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "10-days-wildlife-adventure", "14-days-complete-sri-lanka"],
  },
  {
    slug: "sigiriya",
    name: "Sigiriya",
    region: "Cultural Triangle",
    province: "Central Province",
    description:
      "Sigiriya Rock Fortress rises from dry-zone jungle as one of Sri Lanka’s most recognisable UNESCO landmarks — frescoes, water gardens, and a summit palace.",
    highlights: ["Rock Fortress", "Water gardens", "Mirror Wall"],
    thingsToDo: ["Sunrise climb", "Garden walk", "Village lunch"],
    nearbyAttractions: ["Pidurangala Rock", "Minneriya (seasonal)", "Dambulla caves"],
    keywords: ["Sigiriya Rock Fortress", "UNESCO"],
    imageSrc: img("sigiriya"),
    imageAlt: "Sigiriya Rock Fortress rising above tropical forest",
    lat: 7.957,
    lng: 80.7603,
    driveFromColomboHours: 4,
    driveFromColomboLabel: "~3.5–4.5 hrs from Colombo",
    bestSeason: "Dec–Apr (drier Triangle)",
    weatherLabel: "Hot dry-zone · start early",
    bestPhotoTime: "Soft morning light on the rock",
    unesco: true,
    relatedPackageSlugs: ["3-days-cultural-triangle", "7-days-best-of-sri-lanka", "14-days-complete-sri-lanka"],
  },
  {
    slug: "dambulla",
    name: "Dambulla",
    region: "Cultural Triangle",
    province: "Central Province",
    description:
      "Dambulla Cave Temple shelters centuries of Buddhist murals and statues inside a natural rock monastery — a contemplative counterpoint to Sigiriya.",
    highlights: ["Cave murals", "Golden Temple", "Hilltop panorama"],
    thingsToDo: ["Cave temple visit", "Market stop", "Viewpoint photos"],
    nearbyAttractions: ["Sigiriya", "Namal Uyana", "Village crafts"],
    keywords: ["Dambulla Cave Temple", "UNESCO"],
    imageSrc: img("dambulla"),
    imageAlt: "Buddha statues inside Dambulla Cave Temple",
    lat: 7.8567,
    lng: 80.6492,
    driveFromColomboHours: 3.5,
    driveFromColomboLabel: "~3–4 hrs from Colombo",
    bestSeason: "Dec–Apr",
    weatherLabel: "Warm inland · shaded caves",
    bestPhotoTime: "Late morning murals (no flash)",
    unesco: true,
    relatedPackageSlugs: ["3-days-cultural-triangle", "7-days-best-of-sri-lanka"],
  },
  {
    slug: "kandy",
    name: "Kandy",
    region: "Central Highlands",
    province: "Central Province",
    description:
      "Kandy, the last royal capital, wraps around a lake beneath forested hills. The Temple of the Tooth remains the spiritual heart of the city.",
    highlights: ["Temple of the Tooth", "Kandy Lake", "Peradeniya Gardens"],
    thingsToDo: ["Temple visit", "Lake walk", "Botanical gardens"],
    nearbyAttractions: ["Udawatta Kele", "Arts & crafts lane", "Bahirawakanda"],
    keywords: ["Temple of the Tooth Kandy"],
    imageSrc: img("kandy"),
    imageAlt: "Temple of the Sacred Tooth Relic in Kandy",
    lat: 7.2906,
    lng: 80.6337,
    driveFromColomboHours: 3,
    driveFromColomboLabel: "~3–3.5 hrs from Colombo",
    bestSeason: "Jan–Apr · cooler evenings",
    weatherLabel: "Mild highland edge · 22–28°C",
    bestPhotoTime: "Evening lights on the lake",
    unesco: true,
    relatedPackageSlugs: ["5-days-hill-country-escape", "7-days-best-of-sri-lanka", "10-days-wildlife-adventure"],
  },
  {
    slug: "nuwara-eliya",
    name: "Nuwara Eliya",
    region: "Tea Country",
    province: "Central Province",
    description:
      "Nuwara Eliya sits high in Sri Lanka’s tea belt — cool air, terraced plantations, and Gregory Lake for misty highland mornings.",
    highlights: ["Tea plantations", "Gregory Lake", "Cool climate"],
    thingsToDo: ["Tea factory visit", "Lake stroll", "Viewpoint drive"],
    nearbyAttractions: ["Hakgala Gardens", "Mackwoods Tea", "Horton Plains (day trip)"],
    keywords: ["Nuwara Eliya tea"],
    imageSrc: img("nuwara-eliya"),
    imageAlt: "Terraced tea plantations near Nuwara Eliya",
    lat: 6.9497,
    lng: 80.7891,
    driveFromColomboHours: 5,
    driveFromColomboLabel: "~5–6 hrs from Colombo",
    bestSeason: "Jan–Mar · clear mornings",
    weatherLabel: "Cool misty · 12–22°C",
    bestPhotoTime: "Soft morning plantation light",
    unesco: false,
    relatedPackageSlugs: ["5-days-hill-country-escape", "7-days-best-of-sri-lanka"],
  },
  {
    slug: "ella",
    name: "Ella",
    region: "Uva Highlands",
    province: "Uva Province",
    description:
      "Ella is the photogenic heart of the hill country — Nine Arches Bridge, ridge walks, and café terraces above tea valleys.",
    highlights: ["Nine Arches Bridge", "Little Adam’s Peak", "Tea valleys"],
    thingsToDo: ["Bridge viewpoint", "Short ridge walk", "Scenic train option"],
    nearbyAttractions: ["Ravana Falls", "Demodara Loop", "Ella Rock"],
    keywords: ["Nine Arches Bridge Ella"],
    imageSrc: img("ella"),
    imageAlt: "Nine Arches Bridge in Ella with a blue train",
    lat: 6.8667,
    lng: 81.0466,
    driveFromColomboHours: 6,
    driveFromColomboLabel: "~6–7 hrs from Colombo",
    bestSeason: "Jan–Apr · misty drama year-round",
    weatherLabel: "Cool highland · pack a layer",
    bestPhotoTime: "Golden hour at Nine Arches",
    unesco: false,
    relatedPackageSlugs: ["5-days-hill-country-escape", "7-days-best-of-sri-lanka", "14-days-complete-sri-lanka"],
  },
  {
    slug: "yala",
    name: "Yala",
    region: "Southeast Wildlife",
    province: "Southern / Uva",
    description:
      "Yala National Park is Sri Lanka’s best-known leopard landscape — scrub jungle, rock outcrops, and lagoons shared by elephants and rich birdlife.",
    highlights: ["Leopard safari", "Elephants", "Dry-zone lagoons"],
    thingsToDo: ["Dawn jeep safari", "Birdwatching", "Park gate timing"],
    nearbyAttractions: ["Kataragama", "Sithulpawwa", "Coastal lagoons"],
    keywords: ["Yala leopard safari"],
    imageSrc: img("yala"),
    imageAlt: "Sri Lankan leopard at a waterhole in Yala National Park",
    lat: 6.3725,
    lng: 81.5185,
    driveFromColomboHours: 5.5,
    driveFromColomboLabel: "~5–6 hrs from Colombo",
    bestSeason: "Feb–Jul often strong for wildlife",
    weatherLabel: "Hot dry-zone · hydrated days",
    bestPhotoTime: "First light on game drives",
    unesco: false,
    relatedPackageSlugs: ["10-days-wildlife-adventure", "14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "galle",
    name: "Galle",
    region: "Southern Coast",
    province: "Southern Province",
    description:
      "Galle Fort is a living Dutch colonial enclave on the southern shore — lighthouse, ocean ramparts, and boutique streets.",
    highlights: ["Fort Lighthouse", "Rampart walks", "Old town"],
    thingsToDo: ["Rampart sunset", "Fort cafés", "Lighthouse photos"],
    nearbyAttractions: ["Unawatuna", "Jungle Beach", "Dutch Hospital"],
    keywords: ["Galle Fort", "UNESCO"],
    imageSrc: img("galle"),
    imageAlt: "Galle Fort Lighthouse on Dutch ramparts",
    lat: 6.0329,
    lng: 80.2168,
    driveFromColomboHours: 2.5,
    driveFromColomboLabel: "~2–3 hrs from Colombo",
    bestSeason: "Dec–Mar (southwest)",
    weatherLabel: "Warm coastal · sea breeze",
    bestPhotoTime: "Sunset on the ramparts",
    unesco: true,
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "10-days-wildlife-adventure", "14-days-complete-sri-lanka"],
  },
  {
    slug: "hikkaduwa",
    name: "Hikkaduwa",
    region: "Southwest Coast",
    province: "Southern Province",
    description:
      "Hikkaduwa is a lively southwest beach town — turquoise reef shallows, surf breaks, and a palm-fringed strip of cafés between Galle and Bentota.",
    highlights: ["Coral reef snorkelling", "Surf beach", "Beach strip"],
    thingsToDo: ["Reef snorkel", "Surf lesson", "Sunset beach walk"],
    nearbyAttractions: ["Galle Fort", "Seenigama temple", "Madu River"],
    keywords: ["Hikkaduwa Beach", "Hikkaduwa coral reef"],
    imageSrc: img("hikkaduwa"),
    imageAlt: "Aerial Hikkaduwa Beach with turquoise reef water and palm-lined coast",
    lat: 6.1395,
    lng: 80.1008,
    driveFromColomboHours: 2.5,
    driveFromColomboLabel: "~2.5–3 hrs from Colombo",
    bestSeason: "Nov–Apr (southwest calm)",
    weatherLabel: "Warm coastal · reef-safe footwear",
    bestPhotoTime: "Midday turquoise water from above",
    unesco: false,
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "14-days-complete-sri-lanka"],
  },
  {
    slug: "mirissa",
    name: "Mirissa",
    region: "Southern Coast",
    province: "Southern Province",
    description:
      "Mirissa is known for Coconut Tree Hill sunsets, a crescent bay, and seasonal whale-watching — a soft landing after highlands or wildlife.",
    highlights: ["Coconut Tree Hill", "Bay beach", "Whale season"],
    thingsToDo: ["Hill sunset", "Beach day", "Seasonal whale boat"],
    nearbyAttractions: ["Weligama", "Secret Beach", "Parrot Rock"],
    keywords: ["Coconut Tree Hill Mirissa"],
    imageSrc: img("mirissa"),
    imageAlt: "Mirissa Beach with palm-lined coastline and turquoise water",
    lat: 5.9483,
    lng: 80.4719,
    driveFromColomboHours: 3,
    driveFromColomboLabel: "~3–3.5 hrs from Colombo",
    bestSeason: "Dec–Apr · whales often Nov–Apr",
    weatherLabel: "Warm tropical · ocean air",
    bestPhotoTime: "Sunset at Coconut Tree Hill",
    unesco: false,
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "10-days-wildlife-adventure"],
  },
  {
    slug: "bentota",
    name: "Bentota",
    region: "Southwest Coast",
    province: "Southern Province",
    description:
      "Bentota offers a wide golden beach and lagoon waterways along the southwest corridor between Colombo and Galle.",
    highlights: ["Bentota Beach", "Lagoon", "Resort calm"],
    thingsToDo: ["Beach day", "Lagoon boat", "River mouth walks"],
    nearbyAttractions: ["Brief Garden", "Kosgoda turtle hatchery", "Madu River"],
    keywords: ["Bentota Beach"],
    imageSrc: img("bentota"),
    imageAlt: "Aerial Bentota Beach with turquoise ocean",
    lat: 6.421,
    lng: 79.9959,
    driveFromColomboHours: 1.5,
    driveFromColomboLabel: "~1.5–2 hrs from Colombo",
    bestSeason: "Dec–Mar",
    weatherLabel: "Warm coastal · resort breeze",
    bestPhotoTime: "Midday turquoise beach tones",
    unesco: false,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "trincomalee",
    name: "Trincomalee",
    region: "Eastern Coast",
    province: "Eastern Province",
    description:
      "Trincomalee and nearby Nilaveli open onto clear east-coast water, with snorkelling around Pigeon Island in season.",
    highlights: ["Nilaveli Beach", "Pigeon Island", "Harbour temples"],
    thingsToDo: ["Nilaveli swim", "Seasonal snorkel", "Koneswaram Temple"],
    nearbyAttractions: ["Pigeon Island", "Fort Frederick", "Marble Beach"],
    keywords: ["Nilaveli Beach"],
    imageSrc: img("trincomalee"),
    imageAlt: "Quiet shoreline near Trincomalee and Nilaveli",
    lat: 8.5874,
    lng: 81.2152,
    driveFromColomboHours: 6.5,
    driveFromColomboLabel: "~6–7 hrs from Colombo",
    bestSeason: "May–Sep (east coast)",
    weatherLabel: "Warm clear · seasonal calm seas",
    bestPhotoTime: "Morning Nilaveli turquoise",
    unesco: false,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "anuradhapura",
    name: "Anuradhapura",
    region: "Cultural Triangle",
    province: "North Central Province",
    description:
      "Anuradhapura is Sri Lanka’s ancient sacred city — monumental stupas including Ruwanwelisaya, monastic ruins, and quiet lakes.",
    highlights: ["Ruwanwelisaya", "Sacred Bodhi", "Ancient reservoirs"],
    thingsToDo: ["Stupa circuit", "Bike the park", "Lake evening"],
    nearbyAttractions: ["Mihintale", "Isurumuniya", "Abhayagiri"],
    keywords: ["Ruwanwelisaya", "UNESCO"],
    imageSrc: img("anuradhapura"),
    imageAlt: "Ruwanwelisaya stupa in Anuradhapura",
    lat: 8.3114,
    lng: 80.4037,
    driveFromColomboHours: 4.5,
    driveFromColomboLabel: "~4–5 hrs from Colombo",
    bestSeason: "Dec–Apr",
    weatherLabel: "Hot dry-zone · modest dress",
    bestPhotoTime: "Soft light on white dagobas",
    unesco: true,
    relatedPackageSlugs: ["3-days-cultural-triangle", "14-days-complete-sri-lanka"],
  },
  {
    slug: "polonnaruwa",
    name: "Polonnaruwa",
    region: "Cultural Triangle",
    province: "North Central Province",
    description:
      "Polonnaruwa preserves Sri Lanka’s medieval capital among lakes and woodland — from the Vatadage to Gal Vihara’s rock-cut Buddhas.",
    highlights: ["Gal Vihara", "Vatadage", "Royal ruins"],
    thingsToDo: ["Gal Vihara", "Cycle the ruins", "Lake views"],
    nearbyAttractions: ["Parakrama Samudra", "Rankoth Vehera", "Minneriya (seasonal)"],
    keywords: ["Gal Vihara", "UNESCO"],
    imageSrc: img("polonnaruwa"),
    imageAlt: "Ancient Polonnaruwa stone shrine with Buddha statue",
    lat: 7.9403,
    lng: 81.0188,
    driveFromColomboHours: 5,
    driveFromColomboLabel: "~5–5.5 hrs from Colombo",
    bestSeason: "Dec–Apr",
    weatherLabel: "Hot inland · shade between sites",
    bestPhotoTime: "Morning at Gal Vihara",
    unesco: true,
    relatedPackageSlugs: ["3-days-cultural-triangle", "14-days-complete-sri-lanka"],
  },
  {
    slug: "arugam-bay",
    name: "Arugam Bay",
    region: "Eastern Coast",
    province: "Eastern Province",
    description:
      "Arugam Bay is Sri Lanka’s celebrated east-coast surf town — long right-hand breaks and a relaxed beach village rhythm.",
    highlights: ["Surf breaks", "Beach evenings", "Lagoons"],
    thingsToDo: ["Surf session", "Lagoon sunset", "Beach cafés"],
    nearbyAttractions: ["Pottuvil lagoon", "Kudumbigala", "Panama beaches"],
    keywords: ["Arugam Bay surfing"],
    imageSrc: img("arugam-bay"),
    imageAlt: "Surfer riding a turquoise wave at Arugam Bay",
    lat: 6.8404,
    lng: 81.836,
    driveFromColomboHours: 7,
    driveFromColomboLabel: "~7–8 hrs from Colombo",
    bestSeason: "Apr–Oct (surf season peaks mid-year)",
    weatherLabel: "Warm coastal · east-season seas",
    bestPhotoTime: "Morning barrels · sunset lagoon",
    unesco: false,
    relatedPackageSlugs: ["21-days-grand-explorer"],
  },
  {
    slug: "jaffna",
    name: "Jaffna",
    region: "Northern Peninsula",
    province: "Northern Province",
    description:
      "Jaffna blends Tamil heritage, lagoon landscapes, and island day trips — from Nallur Kovil to Jaffna Fort and ferry routes to Delft and Nainativu.",
    highlights: ["Nallur Kovil", "Jaffna Fort", "Island ferries"],
    thingsToDo: ["Fort ramparts walk", "Temple visit", "Island excursions"],
    nearbyAttractions: ["Delft Island", "Nainativu", "Casuarina Beach"],
    keywords: ["Jaffna Fort", "Nallur Temple", "Northern Sri Lanka"],
    imageSrc: img("jaffna"),
    imageAlt: "Historic Jaffna Fort ramparts overlooking the lagoon in northern Sri Lanka",
    lat: 9.6615,
    lng: 80.0255,
    driveFromColomboHours: 8,
    driveFromColomboLabel: "~7–9 hrs from Colombo",
    bestSeason: "Jan–Sep (drier north)",
    weatherLabel: "Warm peninsula · start early in summer",
    bestPhotoTime: "Late afternoon on the fort ramparts",
    unesco: false,
    relatedPackageSlugs: [
      "jaffna-heritage-city-tour",
      "delft-island-adventure",
      "nainativu-sacred-island-tour",
      "21-days-grand-explorer",
    ],
  },
  {
    slug: "nallur-kandaswamy-temple",
    name: "Nallur Kandaswamy Temple",
    region: "Cultural / Religious",
    province: "Northern Province",
    description:
      "Nallur Kandaswamy Kovil is Jaffna’s grand Hindu temple — gilded gopuram towers, festival drums, and a sacred heart of Tamil culture on the northern peninsula.",
    highlights: ["Gopuram towers", "Festival season", "Sacred precinct"],
    thingsToDo: ["Temple visit", "Festival timing", "Heritage photography"],
    nearbyAttractions: ["Jaffna Fort", "Jaffna Public Library", "Rio Ice Cream"],
    keywords: [
      "Nallur Kandaswamy Temple",
      "Nallur Kovil",
      "Jaffna temple",
      "Cultural Religious",
      "Northern Sri Lanka",
    ],
    imageSrc: img("nallur-kandaswamy-temple"),
    imageAlt: "Nallur Kandaswamy Temple gopuram rising above Jaffna in northern Sri Lanka",
    lat: 9.6747,
    lng: 80.027,
    driveFromColomboHours: 8,
    driveFromColomboLabel: "~7–9 hrs from Colombo",
    bestSeason: "Jan–Sep (drier north)",
    weatherLabel: "Warm peninsula · modest dress for temples",
    bestPhotoTime: "Morning light on the gopuram",
    unesco: false,
    relatedPackageSlugs: ["jaffna-heritage-city-tour"],
  },
  {
    slug: "delft-island",
    name: "Delft Island",
    region: "Island Experience",
    province: "Northern Province",
    description:
      "Delft Island (Neduntheevu) lies west of Jaffna — wild horses, baobab trees, coral beaches, and Queen’s Tower ruins reached by ferry across the Palk Strait shallows.",
    highlights: ["Ferry crossing", "Wild horses", "Baobab tree", "Coral beach"],
    thingsToDo: ["Island ferry", "Ruins walk", "Beach time"],
    nearbyAttractions: ["Jaffna peninsula", "Nainativu", "Casuarina Beach"],
    keywords: [
      "Delft Island",
      "Neduntheevu",
      "Jaffna islands",
      "Island Experience",
      "wild horses Sri Lanka",
    ],
    imageSrc: img("delft-island"),
    imageAlt: "Ancient coral-stone ruins and palmyra palms on Delft Island (Neduntheevu)",
    lat: 9.5122,
    lng: 79.6958,
    driveFromColomboHours: 8.5,
    driveFromColomboLabel: "Ferry from Jaffna · ~8+ hrs from Colombo",
    bestSeason: "Jan–Sep (calmer ferry windows)",
    weatherLabel: "Open island terrain · sun and sea breeze",
    bestPhotoTime: "Late afternoon on coral beaches",
    unesco: false,
    relatedPackageSlugs: ["delft-island-adventure"],
  },
  {
    slug: "nagadeepa-nainativu",
    name: "Nagadeepa Temple",
    region: "Cultural / Religious",
    province: "Northern Province",
    description:
      "Nagadeepa Purana Viharaya on Nainativu island is among Sri Lanka’s holiest Buddhist sites — reached by boat with Nagapooshani Amman Kovil sharing the sacred isle.",
    highlights: ["Nagadeepa Temple", "Nagapooshani Amman", "Boat crossing"],
    thingsToDo: ["Temple pilgrimage", "Island boat ride", "Cultural visit"],
    nearbyAttractions: ["Jaffna peninsula", "Delft Island", "Nallur Kovil"],
    keywords: [
      "Nagadeepa Temple",
      "Nainativu",
      "Nagapooshani Amman",
      "Jaffna pilgrimage",
      "Cultural Religious",
    ],
    imageSrc: img("nagadeepa-nainativu"),
    imageAlt: "Sacred Nagadeepa Purana Vihara on Nainativu island reached by boat from Jaffna",
    lat: 9.6011,
    lng: 79.7717,
    driveFromColomboHours: 8.5,
    driveFromColomboLabel: "Boat from Jaffna · ~8+ hrs from Colombo",
    bestSeason: "Year-round · calmer seas Jan–Sep",
    weatherLabel: "Island pilgrimage · modest temple dress",
    bestPhotoTime: "Soft morning light after the boat crossing",
    unesco: false,
    relatedPackageSlugs: ["nainativu-sacred-island-tour"],
  },
  {
    slug: "sinharaja",
    name: "Sinharaja",
    region: "Rainforest",
    province: "Sabaragamuwa / Southern",
    description:
      "Sinharaja Forest Reserve is Sri Lanka’s last great tropical rainforest — endemic birds, lush canopy trails, and UNESCO-listed biodiversity in the wet zone hills.",
    highlights: ["Rainforest trails", "Endemic wildlife", "UNESCO biosphere"],
    thingsToDo: ["Guided forest walk", "Birdwatching", "Waterfall viewpoints"],
    nearbyAttractions: ["Udawalawe (day trip)", "Ratnapura gems", "Kalawana villages"],
    keywords: ["Sinharaja Forest", "UNESCO rainforest"],
    imageSrc: img("sinharaja"),
    imageAlt: "Green pit viper among foliage in Sinharaja rainforest",
    lat: 6.4167,
    lng: 80.4167,
    driveFromColomboHours: 3.5,
    driveFromColomboLabel: "~3–4 hrs from Colombo",
    bestSeason: "Jan–Apr · drier windows",
    weatherLabel: "Humid rainforest · leech socks advised",
    bestPhotoTime: "Early morning on forest trails",
    unesco: true,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "mannar",
    name: "Mannar",
    region: "Northern Coast",
    province: "Northern Province",
    description:
      "Mannar Island opens onto pale sandbars, baobab trees, and the Talaimannar lighthouse — the western tip of Sri Lanka facing Adam’s Bridge.",
    highlights: ["Talaimannar lighthouse", "Baobab trees", "Adam’s Bridge views"],
    thingsToDo: ["Lighthouse visit", "Island birding", "Sunset beach walks"],
    nearbyAttractions: ["Adam’s Bridge", "Giant’s Tank", "Madhu Church"],
    keywords: ["Mannar", "Talaimannar", "Northern coast"],
    imageSrc: img("mannar"),
    imageAlt: "Talaimannar lighthouse on Mannar Island at sunset",
    lat: 8.981,
    lng: 79.9044,
    driveFromColomboHours: 7,
    driveFromColomboLabel: "~6–8 hrs from Colombo",
    bestSeason: "Feb–Sep (drier north-west)",
    weatherLabel: "Hot coastal · strong sun",
    bestPhotoTime: "Golden hour at the lighthouse",
    unesco: false,
    relatedPackageSlugs: ["jaffna-heritage-city-tour", "21-days-grand-explorer"],
  },
  {
    slug: "kalpitiya",
    name: "Kalpitiya",
    region: "North-West Coast",
    province: "North Western Province",
    description:
      "Kalpitiya Peninsula is famed for spinner dolphin pods, kitesurfing lagoons, and quiet barrier islands on the north-west coast.",
    highlights: ["Dolphin watching", "Kitesurfing", "Bar Reef snorkel"],
    thingsToDo: ["Dawn dolphin boat", "Lagoon kitesurf", "Island hop"],
    nearbyAttractions: ["Bar Reef", "Dutch Bay", "Wilpattu (safari day trip)"],
    keywords: ["Kalpitiya dolphins", "kitesurfing Sri Lanka"],
    imageSrc: img("kalpitiya"),
    imageAlt: "Spinner dolphins leaping in the waters off Kalpitiya",
    lat: 8.2282,
    lng: 79.7597,
    driveFromColomboHours: 3.5,
    driveFromColomboLabel: "~3–4 hrs from Colombo",
    bestSeason: "Nov–Apr (dolphin season peaks)",
    weatherLabel: "Warm coastal · early boat departures",
    bestPhotoTime: "Sunrise dolphin trips",
    unesco: false,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "liptons-seat",
    name: "Lipton's Seat",
    region: "Tea Country",
    province: "Uva Province",
    description:
      "Lipton’s Seat crowns Haputale ridge with 360° views over emerald tea estates — the panorama Sir Thomas Lipton once surveyed.",
    highlights: ["Panoramic viewpoint", "Tea valleys", "Haputale ridge"],
    thingsToDo: ["Sunrise viewpoint", "Tea walk", "Tuk ride to summit"],
    nearbyAttractions: ["Dambatenne factory", "Haputale town", "Ella day trip"],
    keywords: ["Lipton's Seat", "Haputale tea"],
    imageSrc: img("liptons-seat"),
    imageAlt: "Rolling tea plantations viewed from Lipton's Seat near Haputale",
    lat: 6.78,
    lng: 80.958,
    driveFromColomboHours: 5.5,
    driveFromColomboLabel: "~5–6 hrs from Colombo",
    bestSeason: "Jan–Apr · clear mornings",
    weatherLabel: "Cool misty highland · wrap up at dawn",
    bestPhotoTime: "Sunrise above the tea carpet",
    unesco: false,
    relatedPackageSlugs: ["5-days-hill-country-escape", "7-days-best-of-sri-lanka"],
  },
  {
    slug: "badulla",
    name: "Badulla",
    region: "Uva Highlands",
    province: "Uva Province",
    description:
      "Badulla is the scenic terminus of the hill-country railway — misty valleys, colonial station charm, and the gateway to Ella and Diyaluma.",
    highlights: ["Railway terminus", "Hill views", "Muthiyangana Temple"],
    thingsToDo: ["Scenic train ride", "Town temple visit", "Waterfall day trips"],
    nearbyAttractions: ["Diyaluma Falls", "Ella", "Dunhinda Falls"],
    keywords: ["Badulla railway", "hill country train"],
    imageSrc: img("badulla"),
    imageAlt: "Badulla railway station with a red train at the platform",
    lat: 6.9934,
    lng: 81.055,
    driveFromColomboHours: 6,
    driveFromColomboLabel: "~6–7 hrs from Colombo",
    bestSeason: "Jan–Apr",
    weatherLabel: "Cool upland · afternoon showers possible",
    bestPhotoTime: "Morning train arrivals",
    unesco: false,
    relatedPackageSlugs: ["5-days-hill-country-escape", "14-days-complete-sri-lanka"],
  },
  {
    slug: "ratnapura",
    name: "Ratnapura",
    region: "Sabaragamuwa",
    province: "Sabaragamuwa Province",
    description:
      "Ratnapura — the City of Gems — sits beneath the sacred silhouette of Adam’s Peak, surrounded by tea-clad hills and gem-country rivers.",
    highlights: ["Gem museums", "Adam's Peak views", "Sinharaja access"],
    thingsToDo: ["Gem mine visit", "Peak pilgrimage (seasonal)", "Rainforest day trip"],
    nearbyAttractions: ["Sinharaja", "Bopath Ella", "Sri Pada trail"],
    keywords: ["Ratnapura gems", "Adam's Peak", "Sri Pada"],
    imageSrc: img("ratnapura"),
    imageAlt: "Adam's Peak rising above tea plantations near Ratnapura",
    lat: 6.6828,
    lng: 80.3992,
    driveFromColomboHours: 3,
    driveFromColomboLabel: "~2.5–3.5 hrs from Colombo",
    bestSeason: "Dec–May (Pilgrimage Dec–May)",
    weatherLabel: "Humid lowland hills · mist on peaks",
    bestPhotoTime: "Clear morning views of Sri Pada",
    unesco: false,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "ayurveda-wellness",
    name: "Ayurveda Wellness",
    region: "Wellness Coast",
    province: "Western Province",
    description:
      "Sri Lanka’s Ayurveda retreats blend herbal oils, steam poultice therapies, and coastal calm — a restorative pause on the southwest wellness corridor.",
    highlights: ["Ayurvedic massage", "Herbal therapies", "Coastal retreats"],
    thingsToDo: ["Pinda sweda treatment", "Consultation", "Yoga & diet plan"],
    nearbyAttractions: ["Bentota lagoon", "Beruwala beach", "Brief Garden"],
    keywords: ["Ayurveda Sri Lanka", "wellness retreat", "spa holiday"],
    imageSrc: img("ayurveda-wellness"),
    imageAlt: "Traditional Ayurvedic herbal poultice massage treatment",
    lat: 6.4784,
    lng: 79.9826,
    driveFromColomboHours: 1.5,
    driveFromColomboLabel: "~1.5 hrs from Colombo",
    bestSeason: "Year-round retreats",
    weatherLabel: "Warm coastal spa climate",
    bestPhotoTime: "Soft indoor treatment lighting",
    unesco: false,
    relatedPackageSlugs: ["7-days-best-of-sri-lanka", "14-days-complete-sri-lanka"],
  },
  {
    slug: "tissamaharama",
    name: "Tissamaharama",
    region: "Southern Wildlife",
    province: "Southern Province",
    description:
      "Tissamaharama’s ancient dagoba rises above emerald paddy fields — a serene gateway to Yala safaris and the sacred lakes of the deep south.",
    highlights: ["Tissa Dagoba", "Yala access", "Paddy landscapes"],
    thingsToDo: ["Stupa visit", "Lake walk", "Safari departure point"],
    nearbyAttractions: ["Yala National Park", "Kataragama", "Bundala birds"],
    keywords: ["Tissamaharama", "Tissa Dagoba", "Yala gateway"],
    imageSrc: img("tissamaharama"),
    imageAlt: "White Tissamaharama dagoba above green paddy fields under dramatic skies",
    lat: 6.2794,
    lng: 81.2872,
    driveFromColomboHours: 5,
    driveFromColomboLabel: "~5–6 hrs from Colombo",
    bestSeason: "Feb–Jul for Yala wildlife",
    weatherLabel: "Hot dry-zone · start safaris early",
    bestPhotoTime: "Late afternoon on the paddy plain",
    unesco: false,
    relatedPackageSlugs: ["10-days-wildlife-adventure", "14-days-complete-sri-lanka"],
  },
  {
    slug: "batticaloa",
    name: "Batticaloa",
    region: "Eastern Coast",
    province: "Eastern Province",
    description:
      "Batticaloa — the singing fish lagoon city — blends Tamil heritage, lagoon promenades, and quiet east-coast beaches away from the crowds.",
    highlights: ["Lagoon promenade", "Kallady Bridge", "Historic gate"],
    thingsToDo: ["Lagoon walk", "Heritage sites", "Beach time at Pasikuda (day trip)"],
    nearbyAttractions: ["Pasikuda", "Kalkudah", "Batticaloa Fort"],
    keywords: ["Batticaloa", "singing fish lagoon", "east coast"],
    imageSrc: img("batticaloa"),
    imageAlt: "Batticaloa lagoon promenade with stone arches and palm-lined waterfront",
    lat: 7.7102,
    lng: 81.6924,
    driveFromColomboHours: 6.5,
    driveFromColomboLabel: "~6–7 hrs from Colombo",
    bestSeason: "May–Sep (east coast calm)",
    weatherLabel: "Warm lagoon climate · sea breeze",
    bestPhotoTime: "Blue-hour lagoon reflections",
    unesco: false,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "munneswaram",
    name: "Munneswaram",
    region: "Cultural / Religious",
    province: "North Western Province",
    description:
      "Munneswaram Kovil near Chilaw is one of Sri Lanka’s most colourful Hindu temples — towering gopurams and centuries of pilgrimage on the northwest coast.",
    highlights: ["Colourful gopurams", "Shiva kovil", "Pilgrimage site"],
    thingsToDo: ["Temple visit", "Festival timing", "Chilaw seafood stop"],
    nearbyAttractions: ["Chilaw beach", "Wilpattu (safari)", "Kalpitiya coast"],
    keywords: ["Munneswaram Temple", "Munneswaram Kovil", "Chilaw"],
    imageSrc: img("munneswaram"),
    imageAlt: "Vibrant gopuram towers of Munneswaram Hindu temple near Chilaw",
    lat: 7.5833,
    lng: 79.8167,
    driveFromColomboHours: 2,
    driveFromColomboLabel: "~2 hrs from Colombo",
    bestSeason: "Year-round · Navaratri vibrant",
    weatherLabel: "Warm coastal · modest temple dress",
    bestPhotoTime: "Morning light on the gopurams",
    unesco: false,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "horton-plains",
    name: "Horton Plains",
    region: "Central Highlands",
    province: "Central Province",
    description:
      "Horton Plains National Park is a misty montane plateau — sambar deer on open grasslands, Baker’s Falls, and the dramatic World’s End cliff above the hill country.",
    highlights: ["World's End", "Sambar deer", "Baker's Falls"],
    thingsToDo: ["Dawn plateau hike", "Wildlife spotting", "Tea-country day trip from Nuwara Eliya"],
    nearbyAttractions: ["Nuwara Eliya", "Ambewela farms", "Ohiya railway"],
    keywords: ["Horton Plains", "World's End", "sambar deer"],
    imageSrc: img("horton-plains"),
    imageAlt: "Sambar deer grazing on Horton Plains grasslands under misty highland skies",
    lat: 6.802,
    lng: 80.8071,
    driveFromColomboHours: 5,
    driveFromColomboLabel: "~5 hrs from Colombo",
    bestSeason: "Jan–Mar clearer mornings",
    weatherLabel: "Cool highland · mist and wind",
    bestPhotoTime: "Early morning before clouds close in",
    unesco: true,
    relatedPackageSlugs: ["14-days-complete-sri-lanka", "21-days-grand-explorer"],
  },
  {
    slug: "udawalawe",
    name: "Udawalawe",
    region: "Southern Wildlife",
    province: "Uva / Sabaragamuwa",
    description:
      "Udawalawe National Park offers reliable elephant sightings across open grasslands and reservoir edges — one of Sri Lanka’s best parks for herds and tuskers year-round.",
    highlights: ["Elephant herds", "Open grasslands", "Reservoir wildlife"],
    thingsToDo: ["Jeep safari", "Elephant Transit Home visit", "Birdwatching"],
    nearbyAttractions: ["Sinharaja (day trip)", "Ella hills", "Embilipitiya"],
    keywords: ["Udawalawe National Park", "elephant safari"],
    imageSrc: img("udawalawe"),
    imageAlt: "Tusker elephant with herd on Udawalawe National Park grasslands",
    lat: 6.4465,
    lng: 80.8828,
    driveFromColomboHours: 4,
    driveFromColomboLabel: "~4 hrs from Colombo",
    bestSeason: "Year-round elephant sightings",
    weatherLabel: "Warm dry-zone · start safaris early",
    bestPhotoTime: "Golden hour on the grasslands",
    unesco: false,
    relatedPackageSlugs: ["10-days-wildlife-adventure", "14-days-complete-sri-lanka"],
  },
];
